// Migrations will be generated by the QUESTPIE CLI.
// Run: bun questpie migrate
//
// This file exports all migrations for the CMS to apply.

import type { Migration } from "questpie";

export const migrations: Migration[] = [];
