/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiPreviewRouteImport } from './routes/api/preview'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppBookingRouteImport } from './routes/_app/booking'
import { Route as AppBarbersIndexRouteImport } from './routes/_app/barbers.index'
import { Route as ApiCmsSplatRouteImport } from './routes/api/cms/$'
import { Route as AppPagesSlugRouteImport } from './routes/_app/pages.$slug'
import { Route as AppBarbersSlugRouteImport } from './routes/_app/barbers.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingRoute = AppBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AppRoute,
} as any)
const AppBarbersIndexRoute = AppBarbersIndexRouteImport.update({
  id: '/barbers/',
  path: '/barbers/',
  getParentRoute: () => AppRoute,
} as any)
const ApiCmsSplatRoute = ApiCmsSplatRouteImport.update({
  id: '/api/cms/$',
  path: '/api/cms/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPagesSlugRoute = AppPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBarbersSlugRoute = AppBarbersSlugRouteImport.update({
  id: '/barbers/$slug',
  path: '/barbers/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof AppBookingRoute
  '/contact': typeof AppContactRoute
  '/services': typeof AppServicesRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/preview': typeof ApiPreviewRoute
  '/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/barbers/$slug': typeof AppBarbersSlugRoute
  '/pages/$slug': typeof AppPagesSlugRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
  '/barbers': typeof AppBarbersIndexRoute
}
export interface FileRoutesByTo {
  '/booking': typeof AppBookingRoute
  '/contact': typeof AppContactRoute
  '/services': typeof AppServicesRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/preview': typeof ApiPreviewRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/barbers/$slug': typeof AppBarbersSlugRoute
  '/pages/$slug': typeof AppPagesSlugRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
  '/barbers': typeof AppBarbersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_app/booking': typeof AppBookingRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/services': typeof AppServicesRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/preview': typeof ApiPreviewRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/barbers/$slug': typeof AppBarbersSlugRoute
  '/_app/pages/$slug': typeof AppPagesSlugRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
  '/_app/barbers/': typeof AppBarbersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/booking'
    | '/contact'
    | '/services'
    | '/admin/$'
    | '/admin/login'
    | '/api/preview'
    | '/'
    | '/admin/'
    | '/barbers/$slug'
    | '/pages/$slug'
    | '/api/cms/$'
    | '/barbers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/booking'
    | '/contact'
    | '/services'
    | '/admin/$'
    | '/admin/login'
    | '/api/preview'
    | '/'
    | '/admin'
    | '/barbers/$slug'
    | '/pages/$slug'
    | '/api/cms/$'
    | '/barbers'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/booking'
    | '/_app/contact'
    | '/_app/services'
    | '/admin/$'
    | '/admin/login'
    | '/api/preview'
    | '/_app/'
    | '/admin/'
    | '/_app/barbers/$slug'
    | '/_app/pages/$slug'
    | '/api/cms/$'
    | '/_app/barbers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiPreviewRoute: typeof ApiPreviewRoute
  ApiCmsSplatRoute: typeof ApiCmsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/booking': {
      id: '/_app/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AppBookingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barbers/': {
      id: '/_app/barbers/'
      path: '/barbers'
      fullPath: '/barbers'
      preLoaderRoute: typeof AppBarbersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/cms/$': {
      id: '/api/cms/$'
      path: '/api/cms/$'
      fullPath: '/api/cms/$'
      preLoaderRoute: typeof ApiCmsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pages/$slug': {
      id: '/_app/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof AppPagesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barbers/$slug': {
      id: '/_app/barbers/$slug'
      path: '/barbers/$slug'
      fullPath: '/barbers/$slug'
      preLoaderRoute: typeof AppBarbersSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBookingRoute: typeof AppBookingRoute
  AppContactRoute: typeof AppContactRoute
  AppServicesRoute: typeof AppServicesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBarbersSlugRoute: typeof AppBarbersSlugRoute
  AppPagesSlugRoute: typeof AppPagesSlugRoute
  AppBarbersIndexRoute: typeof AppBarbersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingRoute: AppBookingRoute,
  AppContactRoute: AppContactRoute,
  AppServicesRoute: AppServicesRoute,
  AppIndexRoute: AppIndexRoute,
  AppBarbersSlugRoute: AppBarbersSlugRoute,
  AppPagesSlugRoute: AppPagesSlugRoute,
  AppBarbersIndexRoute: AppBarbersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiPreviewRoute: ApiPreviewRoute,
  ApiCmsSplatRoute: ApiCmsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
