export declare const heroBlock: any;
export declare const servicesBlock: any;
export declare const teamBlock: any;
export declare const reviewsBlock: any;
export declare const ctaBlock: any;
export declare const bookingCtaBlock: any;
export declare const barbersFeaturedBlock: any;
export declare const servicesFeaturedBlock: any;
export declare const reviewsGridBlock: any;
export declare const textBlock: any;
export declare const headingBlock: any;
export declare const hoursBlock: any;
export declare const contactInfoBlock: any;
export declare const galleryBlock: any;
export declare const imageTextBlock: any;
export declare const statsBlock: any;
export declare const columnsBlock: any;
export declare const spacerBlock: any;
export declare const dividerBlock: any;
export declare const blocks: {
    hero: any;
    text: any;
    heading: any;
    services: any;
    team: any;
    reviews: any;
    cta: any;
    columns: any;
    spacer: any;
    divider: any;
    hours: any;
    "contact-info": any;
    "booking-cta": any;
    gallery: any;
    "image-text": any;
    stats: any;
    "barbers-featured": any;
    "services-featured": any;
    "reviews-grid": any;
};
