/* eslint-disable */
// Hand-written module definition — will be auto-generated by codegen in future.
// Follows the pattern from packages/admin/src/server/modules/admin/.generated/module.ts

// ── Collections ────────────────────────────────────────────
import { wfEventCollection as _coll_wf_event } from "../collections/wf-event.js";
import { wfInstanceCollection as _coll_wf_instance } from "../collections/wf-instance.js";
import { wfLogCollection as _coll_wf_log } from "../collections/wf-log.js";
import { wfStepCollection as _coll_wf_step } from "../collections/wf-step.js";

// ── Jobs ───────────────────────────────────────────────────
import { wfExecuteJob as _job_wf_execute } from "../jobs/wf-execute.js";
import { wfMaintenanceJob as _job_wf_maintenance } from "../jobs/wf-maintenance.js";
import { wfResumeJob as _job_wf_resume } from "../jobs/wf-resume.js";

// ── Services ───────────────────────────────────────────────
import { workflowService as _svc_workflows } from "../services/workflow-service.js";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface WorkflowsCollections {
	wf_instance: typeof _coll_wf_instance;
	wf_step: typeof _coll_wf_step;
	wf_event: typeof _coll_wf_event;
	wf_log: typeof _coll_wf_log;
}

export interface WorkflowsJobs {
	"questpie-wf-execute": typeof _job_wf_execute;
	"questpie-wf-resume": typeof _job_wf_resume;
	"questpie-wf-maintenance": typeof _job_wf_maintenance;
}

export interface WorkflowsServices {
	workflows: typeof _svc_workflows;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-workflows" as const,
	collections: {
		wf_instance: _coll_wf_instance,
		wf_step: _coll_wf_step,
		wf_event: _coll_wf_event,
		wf_log: _coll_wf_log,
	} as WorkflowsCollections,
	globals: {},
	functions: {},
	jobs: {
		"questpie-wf-execute": _job_wf_execute,
		"questpie-wf-resume": _job_wf_resume,
		"questpie-wf-maintenance": _job_wf_maintenance,
	} as WorkflowsJobs,
	routes: {},
	messages: {},
	services: {
		workflows: _svc_workflows,
	} as WorkflowsServices,
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
};

export type WorkflowsModule = typeof _module;
export default _module;
