/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { wfEventCollection as _coll_wf_event } from "../collections/wf-event";
import { wfInstanceCollection as _coll_wf_instance } from "../collections/wf-instance";
import { wfLogCollection as _coll_wf_log } from "../collections/wf-log";
import { wfStepCollection as _coll_wf_step } from "../collections/wf-step";
// ── Singles ────────────────────────────────────────────────
import _dashboard from "../dashboard";
// ── Jobs ────────────────────────────────────────────
import _job_wfExecute from "../jobs/wf-execute";
import _job_wfMaintenance from "../jobs/wf-maintenance";
import _job_wfResume from "../jobs/wf-resume";
// ── Routes ────────────────────────────────────────────
import { workflowFunctions as _route_workflowFunctions } from "../routes/workflow-functions";
// ── Services ────────────────────────────────────────────
import _svc_workflowService from "../services/workflow-service";
import _sidebar from "../sidebar";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface WorkflowsCollections {
	wf_event: typeof _coll_wf_event;
	wf_instance: typeof _coll_wf_instance;
	wf_log: typeof _coll_wf_log;
	wf_step: typeof _coll_wf_step;
}

export interface WorkflowsJobs {
	wfExecute: typeof _job_wfExecute;
	wfMaintenance: typeof _job_wfMaintenance;
	wfResume: typeof _job_wfResume;
}

export type WorkflowsRoutes = typeof _route_workflowFunctions;

export interface WorkflowsServices {
	workflowService: typeof _svc_workflowService;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-workflows" as const,
	collections: {
		wf_event: _coll_wf_event,
		wf_instance: _coll_wf_instance,
		wf_log: _coll_wf_log,
		wf_step: _coll_wf_step,
	} as WorkflowsCollections,
	jobs: {
		wfExecute: _job_wfExecute,
		wfMaintenance: _job_wfMaintenance,
		wfResume: _job_wfResume,
	} as WorkflowsJobs,
	routes: {
		..._route_workflowFunctions,
	} as WorkflowsRoutes,
	services: {
		workflowService: _svc_workflowService,
	} as WorkflowsServices,
	globals: {},
	messages: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	views: {},
	components: {},
	blocks: {},
	dashboard: [_dashboard],
	sidebar: [_sidebar],
};

export type WorkflowsModule = typeof _module;
export default _module;
