/**
 * Admin Client Template Generator
 *
 * Custom generator for the `admin-client` codegen target.
 * Produces `questpie/admin/.generated/client.ts` — a plain admin config
 * object that replaces `qa().use(adminModule)` setup.
 *
 * The generated file:
 * 1. Imports built-in defaults from `@questpie/admin/client`
 * 2. Imports discovered user files (blocks, views, components, etc.)
 * 3. Merges them into an `AdminBuilder` instance
 * 4. Exports the builder as default
 *
 * @see PLAN-PLUGIN-CONSISTENCY.md §6.2 (admin-client target)
 * @see PLAN-PLUGIN-CONSISTENCY.md §7 (Admin Client Generated Artifact)
 */

import type {
	CodegenTargetGenerateContext,
	CodegenTargetOutput,
	DiscoveredFile,
} from "questpie";

/**
 * Generate the admin client config file.
 *
 * Called by `runAllTargets()` for the `admin-client` target.
 */
export function generateAdminClientTemplate(
	ctx: CodegenTargetGenerateContext,
): CodegenTargetOutput {
	const lines: string[] = [];
	const imports: string[] = [];

	// Header
	lines.push("/**");
	lines.push(" * Admin Client Config");
	lines.push(" *");
	lines.push(" * Auto-generated by questpie codegen — do not edit.");
	lines.push(" * This file replaces manual `qa().use(adminModule)` setup.");
	lines.push(" */");
	lines.push("");

	// Core imports — always present
	imports.push(
		'import { AdminBuilder, coreAdminModule } from "@questpie/admin/client";',
	);

	// Collect discovered files by category
	const blocks = ctx.discovered.categories.get("blocks");
	const views = ctx.discovered.categories.get("views");
	const components = ctx.discovered.categories.get("components");
	const fields = ctx.discovered.categories.get("fields");
	const pages = ctx.discovered.categories.get("pages");
	const widgets = ctx.discovered.categories.get("widgets");

	// Import discovered files
	const importLines: string[] = [];
	const categories = [
		{ name: "blocks", files: blocks },
		{ name: "views", files: views },
		{ name: "components", files: components },
		{ name: "fields", files: fields },
		{ name: "pages", files: pages },
		{ name: "widgets", files: widgets },
	];

	for (const { files } of categories) {
		if (!files || files.size === 0) continue;
		for (const file of files.values()) {
			importLines.push(generateImportLine(file));
		}
	}

	// Import discovered singles (locale, translations, etc.)
	for (const [key, file] of ctx.discovered.singles) {
		importLines.push(generateImportLine(file));
	}

	// Add extra imports from transforms
	for (const imp of ctx.extraImports) {
		imports.push(`import ${imp.name} from "${imp.path}";`);
	}

	// Emit all imports
	lines.push(...imports);
	if (importLines.length > 0) {
		lines.push("");
		lines.push(...importLines);
	}
	lines.push("");

	// Build the admin config
	lines.push("// Start with built-in defaults");
	lines.push("let _admin = coreAdminModule;");
	lines.push("");

	// Merge discovered blocks
	if (blocks && blocks.size > 0) {
		const blockEntries = [...blocks.values()]
			.sort((a, b) => a.key.localeCompare(b.key))
			.map((f) => `\t${JSON.stringify(f.key)}: ${f.varName},`)
			.join("\n");
		lines.push("// User-defined block renderers");
		lines.push("_admin = _admin.blocks({");
		lines.push(blockEntries);
		lines.push("}) as typeof _admin;");
		lines.push("");
	}

	// Merge discovered views
	if (views && views.size > 0) {
		const viewEntries = [...views.values()]
			.sort((a, b) => a.key.localeCompare(b.key))
			.map((f) => `\t${JSON.stringify(f.key)}: ${f.varName},`)
			.join("\n");
		lines.push("// User-defined views");
		lines.push("_admin = _admin.views({");
		lines.push(viewEntries);
		lines.push("}) as typeof _admin;");
		lines.push("");
	}

	// Merge discovered components
	if (components && components.size > 0) {
		const compEntries = [...components.values()]
			.sort((a, b) => a.key.localeCompare(b.key))
			.map((f) => `\t${JSON.stringify(f.key)}: ${f.varName},`)
			.join("\n");
		lines.push("// User-defined components");
		lines.push("_admin = _admin.components({");
		lines.push(compEntries);
		lines.push("}) as typeof _admin;");
		lines.push("");
	}

	// Merge discovered fields
	if (fields && fields.size > 0) {
		const fieldEntries = [...fields.values()]
			.sort((a, b) => a.key.localeCompare(b.key))
			.map((f) => `\t${JSON.stringify(f.key)}: ${f.varName},`)
			.join("\n");
		lines.push("// User-defined fields");
		lines.push("_admin = _admin.fields({");
		lines.push(fieldEntries);
		lines.push("}) as typeof _admin;");
		lines.push("");
	}

	// Merge discovered pages
	if (pages && pages.size > 0) {
		const pageEntries = [...pages.values()]
			.sort((a, b) => a.key.localeCompare(b.key))
			.map((f) => `\t${JSON.stringify(f.key)}: ${f.varName},`)
			.join("\n");
		lines.push("// User-defined pages");
		lines.push("_admin = _admin.pages({");
		lines.push(pageEntries);
		lines.push("}) as typeof _admin;");
		lines.push("");
	}

	// Merge discovered widgets
	if (widgets && widgets.size > 0) {
		const widgetEntries = [...widgets.values()]
			.sort((a, b) => a.key.localeCompare(b.key))
			.map((f) => `\t${JSON.stringify(f.key)}: ${f.varName},`)
			.join("\n");
		lines.push("// User-defined widgets");
		lines.push("_admin = _admin.widgets({");
		lines.push(widgetEntries);
		lines.push("}) as typeof _admin;");
		lines.push("");
	}

	// Handle extra runtime code from transforms
	if (ctx.extraRuntimeCode.length > 0) {
		lines.push("// Plugin-contributed runtime");
		for (const code of ctx.extraRuntimeCode) {
			lines.push(code);
		}
		lines.push("");
	}

	// Handle extra type declarations
	if (ctx.extraTypeDeclarations.length > 0) {
		lines.push("// Type declarations");
		for (const decl of ctx.extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// Export
	lines.push("export default _admin;");
	lines.push("");

	return { code: lines.join("\n") };
}

// ============================================================================
// Helpers
// ============================================================================

/**
 * Generate an import line for a discovered file.
 */
function generateImportLine(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	return `import ${file.varName} from "${file.importPath}";`;
}
