/**
 * Admin Projection Validator
 *
 * Cross-target validator that ensures server-side references (blocks, views,
 * components) have matching registrations in the admin-client target.
 *
 * When a server `blocks/` directory contains `hero.ts`, the admin `blocks/`
 * directory must also contain a `hero.tsx` renderer. If not, codegen fails
 * with an actionable error message.
 *
 * This validator is registered on `adminPlugin().validators` and runs
 * automatically after all targets are generated by `runAllTargets()`.
 *
 * @see PLAN-PLUGIN-CONSISTENCY.md §9 (Projection Quality Gate)
 */

import type {
	CodegenResult,
	CrossTargetValidator,
	ProjectionError,
} from "questpie";

/**
 * Category projections to validate between server and admin-client.
 *
 * Each entry describes a server-side category whose discovered keys
 * must have a corresponding key in the admin-client target.
 *
 * `serverCategory` = category name in the "server" target discovery
 * `clientCategory` = category name in the "admin-client" target discovery
 * `suggestedDir`   = where the user should create the missing file
 */
const PROJECTION_CHECKS = [
	{
		serverCategory: "blocks",
		clientCategory: "blocks",
		suggestedDir: "questpie/admin/blocks",
		label: "block renderer",
	},
	{
		serverCategory: "views",
		clientCategory: "views",
		suggestedDir: "questpie/admin/views",
		label: "view definition",
	},
	{
		serverCategory: "components",
		clientCategory: "components",
		suggestedDir: "questpie/admin/components",
		label: "component definition",
	},
] as const;

/**
 * Create a cross-target validator for admin projection checks.
 *
 * Compares discovered file keys between the "server" and "admin-client"
 * targets. Any key present in the server target but missing from the
 * admin-client target produces an error.
 *
 * @returns A `CrossTargetValidator` function
 */
export function createAdminProjectionValidator(): CrossTargetValidator {
	return (targets: Map<string, CodegenResult>): ProjectionError[] => {
		const serverResult = targets.get("server");
		const adminClientResult = targets.get("admin-client");

		// If either target is missing, skip validation.
		// This handles the case where adminPlugin() is registered but the
		// admin directory doesn't exist yet (no admin-client target generated).
		if (!serverResult || !adminClientResult) {
			return [];
		}

		const errors: ProjectionError[] = [];

		for (const check of PROJECTION_CHECKS) {
			const serverFiles = serverResult.discovered.categories.get(
				check.serverCategory,
			);
			const clientFiles = adminClientResult.discovered.categories.get(
				check.clientCategory,
			);

			if (!serverFiles || serverFiles.size === 0) {
				continue;
			}

			// Collect client-side keys for lookup
			const clientKeys = new Set<string>();
			if (clientFiles) {
				for (const key of clientFiles.keys()) {
					clientKeys.add(key);
				}
			}

			// Check each server-side key
			for (const [key, file] of serverFiles) {
				if (!clientKeys.has(key)) {
					errors.push({
						severity: "error",
						category: check.serverCategory,
						key,
						sourceTarget: "server",
						consumerTarget: "admin-client",
						message:
							`Server defines ${check.serverCategory}/${file.key} but no matching ` +
							`${check.label} was found in the admin client. ` +
							`Create a file at ${check.suggestedDir}/${file.key}.tsx to fix this.`,
					});
				}
			}
		}

		return errors;
	};
}
