/**
 * Module Template Generation
 *
 * Generates the `.generated/module.ts` file content for npm package modules.
 * The generated file:
 * 1. Imports all discovered entities (collections, functions, jobs, etc.)
 * 2. Imports sub-modules from `modules.ts` (if present)
 * 3. Emits type interfaces using typeof references (zero inference cost)
 * 4. Exports a plain static module definition object
 *
 * Unlike the root app template (template.ts), this does NOT:
 * - Import a runtime config
 * - Call createApp()
 * - Generate an App type
 *
 * All category-specific behavior is driven by `CategoryDeclaration` metadata
 * from plugins — no hardcoded category names.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.2 (Module — .generated/module.ts)
 */

import type {
	CategoryDeclaration,
	DiscoveredFile,
	DiscoveryResult,
} from "./types.js";

// ============================================================================
// Module template options
// ============================================================================

export interface ModuleTemplateOptions {
	/** Module name (e.g. "questpie-admin", "questpie-audit"). */
	moduleName: string;
	/** Discovery result with all found files. */
	discovered: DiscoveryResult;
	/**
	 * Merged category declarations from all plugins.
	 * Key = category name, value = declaration metadata.
	 * Used to determine emit strategy, type emission, etc.
	 */
	categoryMeta: Map<string, CategoryDeclaration>;
	/** Additional imports from plugins (e.g. admin view/component factories). */
	extraImports?: Array<{ name: string; path: string }>;
	/** Additional type declarations from plugins. */
	extraTypeDeclarations?: string[];
	/**
	 * Additional runtime code to add to the module object.
	 * Each entry is a line like `listViews: { table: listView("table") },`.
	 */
	extraModuleProperties?: string[];
}

// ============================================================================
// Module template generation
// ============================================================================

/**
 * Generate the .generated/module.ts file content for a package module.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.2 (Module — .generated/module.ts)
 */
export function generateModuleTemplate(options: ModuleTemplateOptions): string {
	const lines: string[] = [];
	const {
		moduleName,
		discovered,
		categoryMeta,
		extraImports,
		extraTypeDeclarations,
		extraModuleProperties,
	} = options;

	const modulesFile = discovered.singles.get("modules") ?? null;

	// Derive a PascalCase type prefix from the module name
	// "questpie-admin" → "Admin", "questpie-audit" → "Audit"
	const typePrefix = deriveTypePrefix(moduleName);

	// Header
	lines.push("/* eslint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push("// Regenerate with: questpie generate --module");
	lines.push("");

	// Import sub-modules
	if (modulesFile) {
		lines.push(
			"// ── Sub-Modules ────────────────────────────────────────────",
		);
		lines.push(importStatement(modulesFile));
		lines.push("");
	}

	// Import all categories (collections, globals, jobs, functions, etc.)
	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;
		const label = catName.charAt(0).toUpperCase() + catName.slice(1);
		lines.push(`// ── ${label} ────────────────────────────────────────────`);
		for (const file of sortedValues(fileMap)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import auth
	if (discovered.auth) {
		lines.push(
			"// ── Auth ───────────────────────────────────────────────────",
		);
		lines.push(importStatement(discovered.auth));
		lines.push("");
	}

	// Import singles (locale, hooks, access, context, fields, sidebar, etc.)
	const singles = getNonModuleSingles(discovered.singles);
	if (singles.length > 0) {
		lines.push(
			"// ── Singles ────────────────────────────────────────────────",
		);
		for (const file of singles) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Extra plugin imports
	if (extraImports && extraImports.length > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const imp of extraImports) {
			lines.push(`import ${imp.name} from "${imp.path}";`);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// TYPES — module type extraction
	// ════════════════════════════════════════════════════════════

	// Determine which categories need named type interfaces.
	// Use typeEmit from CategoryDeclaration — skip "none" and "messages".
	const categoriesNeedingTypes = new Set<string>();
	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;
		const decl = categoryMeta.get(catName);
		const typeEmit = decl?.typeEmit ?? "standard";
		// Skip categories that don't produce meaningful named types for modules
		if (typeEmit === "none" || typeEmit === "messages") continue;
		categoriesNeedingTypes.add(catName);
	}

	if (categoriesNeedingTypes.size > 0) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push(
			"// TYPES — composed from typeof references (zero inference cost)",
		);
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		// Always emit simple interfaces (no sub-module extends).
		//
		// Why not `extends _SubCollections`:
		//   Modules declare their OWN collections. When a module overrides a
		//   sub-module's collection (e.g. admin overrides starter's `account` with
		//   .merge().set("admin",...)), the override type is NOT a subtype of the
		//   original — TypeScript's `extends` constraint breaks.
		//
		//   Sub-module collection composition is handled upstream in the root app's
		//   index.ts via `ExtractFromModuleArray` and intersection types. Each module
		//   only needs to declare what IT directly provides.
		//
		// Why emit at all (not just infer from `_module`):
		//   Deep .merge().set() builder chains cause TS7056 ("inferred type exceeds
		//   maximum length"). Named interfaces give TypeScript a stable anchor.
		for (const catName of categoriesNeedingTypes) {
			const fileMap = discovered.categories.get(catName)!;
			const decl = categoryMeta.get(catName);
			const emitStrategy = decl?.emit ?? "record";
			const typeName = `${typePrefix}${catName.charAt(0).toUpperCase() + catName.slice(1)}`;

			if (emitStrategy === "nested") {
				// Nested categories (functions) — only type leaf files,
				// bundle files are opaque (their types are inferred via spread)
				const leafFiles = sortedValues(fileMap).filter((f) => !f.isBundle);
				if (leafFiles.length > 0) {
					lines.push(`export interface ${typeName} {`);
					const leafMap = new Map(leafFiles.map((f) => [f.key, f]));
					const nested = buildNestedStructure(leafMap);
					emitNestedTypeObject(lines, nested, 1);
					lines.push("}");
					lines.push("");
				}
			} else {
				emitSimpleTypeInterface(lines, typeName, fileMap);
			}
		}
	}

	// Extra type declarations from plugins
	if (extraTypeDeclarations && extraTypeDeclarations.length > 0) {
		for (const decl of extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// MODULE DEFINITION — static plain object
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// MODULE DEFINITION — static plain object");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	lines.push("const _module = {");
	lines.push(`\tname: "${moduleName}" as const,`);

	// Sub-modules
	if (modulesFile) {
		lines.push(`\tmodules: ${modulesFile.varName},`);
	}

	// Emit all categories — driven by CategoryDeclaration.emit
	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;
		const decl = categoryMeta.get(catName);
		const emitStrategy = decl?.emit ?? "record";
		const typeEmit = decl?.typeEmit ?? "standard";
		const typeName = `${typePrefix}${catName.charAt(0).toUpperCase() + catName.slice(1)}`;
		const hasNamedType = categoriesNeedingTypes.has(catName);

		if (emitStrategy === "nested") {
			// Nested emission (functions) — spread bundles, nest single-export files
			const leafFiles: DiscoveredFile[] = [];
			const bundleFiles: DiscoveredFile[] = [];
			for (const file of sortedValues(fileMap)) {
				if (file.isBundle) {
					bundleFiles.push(file);
				} else {
					leafFiles.push(file);
				}
			}

			lines.push(`\t${safeKey(catName)}: {`);
			// Bundle files are spread (e.g. ...setupFunctions)
			for (const file of bundleFiles) {
				lines.push(`\t\t...${file.varName},`);
			}
			// Single-export files are nested leaves
			if (leafFiles.length > 0) {
				const leafMap = new Map(leafFiles.map((f) => [f.key, f]));
				const nested = buildNestedStructure(leafMap);
				emitNestedObject(lines, nested, 2);
			}
			lines.push("\t},");
		} else if (emitStrategy === "array") {
			// Array emission (migrations, seeds)
			const vars = sortedValues(fileMap)
				.map((f) => f.varName)
				.join(", ");
			lines.push(`\t${safeKey(catName)}: [${vars}],`);
		} else {
			// Record emission (collections, globals, jobs, messages, etc.)
			lines.push(`\t${safeKey(catName)}: {`);
			for (const file of sortedValues(fileMap)) {
				lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
			}
			if (hasNamedType && typeEmit !== "messages") {
				lines.push(`\t} as ${typeName},`);
			} else {
				lines.push("\t},");
			}
		}
	}

	// Auth
	if (discovered.auth) {
		lines.push(`\tauth: ${discovered.auth.varName},`);
	}

	// Singles (hooks, access, sidebar as array, etc.)
	for (const file of singles) {
		// Some singles are arrays (sidebar, dashboard contributions)
		if (file.key === "sidebar" || file.key === "dashboard") {
			lines.push(`\t${safeKey(file.key)}: [${file.varName}],`);
		} else {
			lines.push(`\t${safeKey(file.key)}: ${file.varName},`);
		}
	}

	// Extra module properties from plugins
	if (extraModuleProperties && extraModuleProperties.length > 0) {
		for (const prop of extraModuleProperties) {
			lines.push(`\t${prop}`);
		}
	}

	lines.push("};");
	lines.push("");

	// Export type and default
	lines.push(`export type ${typePrefix}Module = typeof _module;`);
	lines.push("export default _module;");
	lines.push("");

	return lines.join("\n");
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Derive a PascalCase type prefix from a module name.
 * "questpie-admin" → "Admin"
 * "questpie-audit" → "Audit"
 * "billing" → "Billing"
 */
function deriveTypePrefix(moduleName: string): string {
	// Remove "questpie-" prefix if present
	const name = moduleName.replace(/^questpie-/, "");
	// Split on hyphens and PascalCase
	return name
		.split("-")
		.map((s) => s.charAt(0).toUpperCase() + s.slice(1))
		.join("");
}

/**
 * Get all singles except "modules" (which is handled separately).
 */
function getNonModuleSingles(
	singles: Map<string, DiscoveredFile>,
): DiscoveredFile[] {
	const result: DiscoveredFile[] = [];
	for (const [key, file] of singles) {
		if (key === "modules") continue;
		result.push(file);
	}
	return result.sort((a, b) => a.key.localeCompare(b.key));
}

/**
 * Emit a plain type interface for a module category (no sub-module extends).
 * Always emit named types to prevent TS7056 ("inferred type exceeds maximum
 * length") when collection builder types are deeply nested via .merge().set().
 */
function emitSimpleTypeInterface(
	lines: string[],
	typeName: string,
	fileMap: Map<string, DiscoveredFile>,
): void {
	lines.push(`export interface ${typeName} {`);
	for (const file of sortedValues(fileMap)) {
		lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
	}
	lines.push("}");
	lines.push("");
}

// ============================================================================
// Nested structure builder (for emit: "nested" categories)
// ============================================================================

type NestedNode =
	| { type: "leaf"; varName: string }
	| { type: "branch"; children: Map<string, NestedNode> };

/**
 * Build a nested tree from dot-separated keys.
 * Used for categories with `emit: "nested"` (e.g., functions).
 *
 * "admin.stats" → { admin: { stats: leaf } }
 * "getConfig" → { getConfig: leaf }
 */
function buildNestedStructure(
	files: Map<string, DiscoveredFile>,
): Map<string, NestedNode> {
	const root = new Map<string, NestedNode>();
	for (const file of files.values()) {
		const segments = file.key.split(".");
		let current = root;
		for (let i = 0; i < segments.length; i++) {
			const seg = segments[i];
			const isLast = i === segments.length - 1;
			if (isLast) {
				current.set(seg, { type: "leaf", varName: file.varName });
			} else {
				let node = current.get(seg);
				if (!node || node.type === "leaf") {
					node = { type: "branch", children: new Map() };
					current.set(seg, node);
				}
				current = (node as Extract<NestedNode, { type: "branch" }>).children;
			}
		}
	}
	return root;
}

function emitNestedObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: ${node.varName},`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedObject(lines, node.children, indent + 1);
			lines.push(`${tabs}},`);
		}
	}
}

function emitNestedTypeObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: typeof ${node.varName};`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedTypeObject(lines, node.children, indent + 1);
			lines.push(`${tabs}};`);
		}
	}
}

function sortedValues(map: Map<string, DiscoveredFile>): DiscoveredFile[] {
	return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
}

function importStatement(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	return `import ${file.varName} from "${file.importPath}";`;
}

function safeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return `"${key}"`;
}
