/**
 * Module Template Generation
 *
 * Generates the `.generated/module.ts` file content for npm package modules.
 * The generated file:
 * 1. Imports all discovered entities (collections, functions, jobs, etc.)
 * 2. Imports sub-modules from `modules.ts` (if present)
 * 3. Emits type interfaces using typeof references (zero inference cost)
 * 4. Exports a plain static module definition object
 *
 * Unlike the root app template (template.ts), this does NOT:
 * - Import a runtime config
 * - Call createApp()
 * - Generate an App type
 *
 * All category-specific behavior is driven by `CategoryDeclaration` metadata
 * from plugins — no hardcoded category names.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.2 (Module — .generated/module.ts)
 */

import type {
	CategoryDeclaration,
	DiscoverPattern,
	DiscoveredFile,
	DiscoveryResult,
} from "./types.js";

// ============================================================================
// Module template options
// ============================================================================

export interface ModuleTemplateOptions {
	/** Module name (e.g. "questpie-admin", "questpie-audit"). */
	moduleName: string;
	/** Discovery result with all found files. */
	discovered: DiscoveryResult;
	/**
	 * Merged category declarations from all plugins.
	 * Key = category name, value = declaration metadata.
	 * Used to determine emit strategy, type emission, etc.
	 */
	categoryMeta: Map<string, CategoryDeclaration>;
	/** Additional imports from plugins (e.g. admin view/component factories). */
	extraImports?: Array<{ name: string; path: string }>;
	/** Additional type declarations from plugins. */
	extraTypeDeclarations?: string[];
	/**
	 * Additional runtime code to add to the module object.
	 * Each entry is a line like `listViews: { table: listView("table") },`.
	 */
	extraModuleProperties?: string[];
	/**
	 * Merged discover patterns from the target.
	 * Used to check `registryKey` on singles for Registry augmentation.
	 */
	discoverPatterns?: Record<string, DiscoverPattern>;
}

// ============================================================================
// Module template generation
// ============================================================================

/**
 * Generate the .generated/module.ts file content for a package module.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.2 (Module — .generated/module.ts)
 */
export function generateModuleTemplate(options: ModuleTemplateOptions): string {
	const lines: string[] = [];
	const {
		moduleName,
		discovered,
		categoryMeta,
		extraImports,
		extraTypeDeclarations,
		extraModuleProperties,
	} = options;

	const modulesFile = discovered.singles.get("modules") ?? null;

	// Derive a PascalCase type prefix from the module name
	// "questpie-admin" → "Admin", "questpie-audit" → "Audit"
	const typePrefix = deriveTypePrefix(moduleName);

	// Header
	lines.push("/* eslint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push("// Regenerate with: questpie generate --module");
	lines.push("");

	// Import sub-modules
	if (modulesFile) {
		lines.push(
			"// ── Sub-Modules ────────────────────────────────────────────",
		);
		lines.push(importStatement(modulesFile));
		lines.push("");
	}

	// Import all categories (collections, globals, jobs, functions, etc.)
	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;
		const label = catName.charAt(0).toUpperCase() + catName.slice(1);
		lines.push(`// ── ${label} ────────────────────────────────────────────`);
		for (const file of sortedValues(fileMap)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import singles (auth, locale, hooks, access, context, fields, sidebar, etc.)
	const singles = getNonModuleSingles(discovered.singles);
	if (singles.length > 0) {
		lines.push(
			"// ── Singles ────────────────────────────────────────────────",
		);
		for (const file of singles) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Extra plugin imports
	if (extraImports && extraImports.length > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const imp of extraImports) {
			lines.push(`import ${imp.name} from "${imp.path}";`);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// TYPES — module type extraction
	// ════════════════════════════════════════════════════════════

	// Determine which categories need named type interfaces.
	// Use typeEmit from CategoryDeclaration — skip "none" and "messages".
	const categoriesNeedingTypes = new Set<string>();
	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;
		const decl = categoryMeta.get(catName);
		const typeEmit = decl?.typeEmit ?? "standard";
		// Skip categories that don't produce meaningful named types for modules
		if (typeEmit === "none" || typeEmit === "messages") continue;
		// Skip keyFromProperty categories — file-derived keys would mismatch
		// runtime keys, so the named type would be wrong. Use typeof instead.
		if (decl?.keyFromProperty) continue;
		categoriesNeedingTypes.add(catName);
	}

	if (categoriesNeedingTypes.size > 0) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push(
			"// TYPES — composed from typeof references (zero inference cost)",
		);
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		// Always emit simple interfaces (no sub-module extends).
		//
		// Why not `extends _SubCollections`:
		//   Modules declare their OWN collections. When a module overrides a
		//   sub-module's collection (e.g. admin overrides starter's `account` with
		//   .merge().set("admin",...)), the override type is NOT a subtype of the
		//   original — TypeScript's `extends` constraint breaks.
		//
		//   Sub-module collection composition is handled upstream in the root app's
		//   index.ts via `ExtractFromModuleArray` and intersection types. Each module
		//   only needs to declare what IT directly provides.
		//
		// Why emit at all (not just infer from `_module`):
		//   Deep .merge().set() builder chains cause TS7056 ("inferred type exceeds
		//   maximum length"). Named interfaces give TypeScript a stable anchor.
		for (const catName of categoriesNeedingTypes) {
			const fileMap = discovered.categories.get(catName)!;
			const decl = categoryMeta.get(catName);
			const emitStrategy = decl?.emit ?? "record";
			const typeName = `${typePrefix}${catName.charAt(0).toUpperCase() + catName.slice(1)}`;

			if (emitStrategy === "nested") {
				// Nested categories (functions) — only type leaf files,
				// bundle files are opaque (their types are inferred via spread)
				const leafFiles = sortedValues(fileMap).filter((f) => !f.isBundle);
				if (leafFiles.length > 0) {
					lines.push(`export interface ${typeName} {`);
					const leafMap = new Map(leafFiles.map((f) => [f.key, f]));
					const nested = buildNestedStructure(leafMap);
					emitNestedTypeObject(lines, nested, 1);
					lines.push("}");
					lines.push("");
				} else {
					// All files are bundles — no named type emitted
					categoriesNeedingTypes.delete(catName);
				}
			} else {
				emitSimpleTypeInterface(lines, typeName, fileMap);
			}
		}
	}

	// Extra type declarations from plugins
	if (extraTypeDeclarations && extraTypeDeclarations.length > 0) {
		for (const decl of extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// MODULE DEFINITION — static plain object
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// MODULE DEFINITION — static plain object");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	// Pre-scan extraModuleProperties to identify registry-matching properties.
	// These need separate const declarations BEFORE _module to avoid circular
	// typeof _module references in Registry augmentation:
	//   typeof _module → collections → CollectionBuilder augmentation → Registry
	//   → typeof _module["listViews"] → cycle!
	// By extracting to a separate const, Registry can use typeof _reg_listViews.
	const extractedConsts = new Map<
		string,
		{ constName: string; expression: string }
	>();
	const extraPropNames = new Set<string>();
	if (extraModuleProperties && extraModuleProperties.length > 0) {
		// Build the set of category names that have registryKey — these need extraction
		const registryPropNames = new Set<string>();
		for (const [catName, decl] of categoryMeta) {
			if (decl.registryKey) registryPropNames.add(catName);
		}
		for (const prop of extraModuleProperties) {
			const match = prop.match(/^(\w+)\s*:\s*(.+?),?\s*$/);
			if (match) {
				const [, propName, expression] = match;
				extraPropNames.add(propName);
				if (registryPropNames.has(propName)) {
					const constName = `_reg_${propName}`;
					extractedConsts.set(propName, { constName, expression });
				}
			}
		}
	}

	// Emit extracted consts before _module to break typeof circular references
	if (extractedConsts.size > 0) {
		for (const [, { constName, expression }] of extractedConsts) {
			lines.push(`const ${constName} = ${expression};`);
		}
		lines.push("");
	}

	lines.push("const _module = {");
	lines.push(`\tname: "${moduleName}" as const,`);

	// Sub-modules
	if (modulesFile) {
		lines.push(`\tmodules: ${modulesFile.varName},`);
	}

	// Emit all categories — driven by CategoryDeclaration.emit
	// Track which categories were emitted with files
	const emittedCategories = new Set<string>();

	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;
		emittedCategories.add(catName);
		const decl = categoryMeta.get(catName);
		const emitStrategy = decl?.emit ?? "record";
		const typeEmit = decl?.typeEmit ?? "standard";
		const typeName = `${typePrefix}${catName.charAt(0).toUpperCase() + catName.slice(1)}`;
		const hasNamedType = categoriesNeedingTypes.has(catName);

		if (emitStrategy === "nested") {
			// Nested emission (functions) — spread bundles, nest single-export files
			const leafFiles: DiscoveredFile[] = [];
			const bundleFiles: DiscoveredFile[] = [];
			for (const file of sortedValues(fileMap)) {
				if (file.isBundle) {
					bundleFiles.push(file);
				} else {
					leafFiles.push(file);
				}
			}

			lines.push(`\t${safeKey(catName)}: {`);
			// Bundle files are spread (e.g. ...setupFunctions)
			for (const file of bundleFiles) {
				lines.push(`\t\t...${file.varName},`);
			}
			// Single-export files are nested leaves
			if (leafFiles.length > 0) {
				const leafMap = new Map(leafFiles.map((f) => [f.key, f]));
				const nested = buildNestedStructure(leafMap);
				emitNestedObject(lines, nested, 2);
			}
			lines.push("\t},");
		} else if (emitStrategy === "array") {
			// Array emission (migrations, seeds)
			const vars = sortedValues(fileMap)
				.map((f) => f.varName)
				.join(", ");
			lines.push(`\t${safeKey(catName)}: [${vars}],`);
		} else {
			// Record emission (collections, globals, jobs, messages, etc.)
			lines.push(`\t${safeKey(catName)}: {`);
			for (const file of sortedValues(fileMap)) {
				if (decl?.keyFromProperty) {
					lines.push(`\t\t[${file.varName}.${decl.keyFromProperty}]: ${file.varName},`);
				} else {
					lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
				}
			}
			if (hasNamedType && typeEmit !== "messages") {
				lines.push(`\t} as ${typeName},`);
			} else {
				lines.push("\t},");
			}
		}
	}

	// Emit empty stubs for declared categories with no discovered files.
	// This ensures the module type always includes all target categories,
	// so consumers can spread `module.blocks` without type assertions.
	for (const [catName, decl] of categoryMeta) {
		if (emittedCategories.has(catName)) continue;
		if (extraPropNames.has(catName)) continue; // provided by extraModuleProperties
		const emitStrategy = decl.emit ?? "record";
		if (emitStrategy === "array") {
			lines.push(`\t${safeKey(catName)}: [] as const,`);
		} else {
			lines.push(`\t${safeKey(catName)}: {},`);
		}
	}

	// Singles (auth, hooks, access, sidebar as array, etc.)
	for (const file of singles) {
		// Some singles are arrays (sidebar, dashboard contributions)
		if (file.key === "sidebar" || file.key === "dashboard") {
			lines.push(`\t${safeKey(file.key)}: [${file.varName}],`);
		} else {
			lines.push(`\t${safeKey(file.key)}: ${file.varName},`);
		}
	}

	// Extra module properties from plugins
	if (extraModuleProperties && extraModuleProperties.length > 0) {
		for (const prop of extraModuleProperties) {
			const match = prop.match(/^(\w+)\s*:\s*(.+?),?\s*$/);
			if (match) {
				const [, propName] = match;
				const extracted = extractedConsts.get(propName);
				if (extracted) {
					// Reference the extracted const instead of inline expression
					lines.push(`\t${propName}: ${extracted.constName},`);
				} else {
					lines.push(`\t${prop}`);
				}
			} else {
				lines.push(`\t${prop}`);
			}
		}
	}

	lines.push("};");
	lines.push("");

	// Export type and default
	lines.push(`export type ${typePrefix}Module = typeof _module;`);
	lines.push("export default _module;");
	lines.push("");

	// ════════════════════════════════════════════════════════════
	// Registry augmentation — break circular references
	// ════════════════════════════════════════════════════════════
	//
	// Each module augments the global Registry with its categories that have
	// `registryKey` on their CategoryDeclaration. This way factories.ts can
	// read from Registry without referencing `typeof _modules`, which would
	// create a circular type dependency:
	//   typeof _modules → CollectionBuilder augmentation → Registry → typeof _modules
	//
	{
		const registryLines: string[] = [];

		// Iterate ALL categories with registryKey — unified path for everything
		for (const [catName, decl] of categoryMeta) {
			if (!decl.registryKey) continue;
			const regKey = typeof decl.registryKey === "string" ? decl.registryKey : catName;

			// Check if this category has a named type interface
			const hasNamedType = categoriesNeedingTypes.has(catName);
			const catTypeName = `${typePrefix}${catName.charAt(0).toUpperCase() + catName.slice(1)}`;

			// Check if this property was extracted to a separate const (derived categories like listViews/formViews)
			const extracted = extractedConsts.get(catName);

			if (hasNamedType) {
				registryLines.push(`\t\t${safeKey(regKey)}: ${catTypeName};`);
			} else if (extracted) {
				registryLines.push(`\t\t${safeKey(regKey)}: typeof ${extracted.constName};`);
			} else if (emittedCategories.has(catName)) {
				registryLines.push(`\t\t${safeKey(regKey)}: typeof _module["${catName}"];`);
			} else if (extraPropNames.has(catName)) {
				registryLines.push(`\t\t${safeKey(regKey)}: typeof _module["${catName}"];`);
			} else {
				// No discovered files, no extra property — skip to avoid conflicts
				continue;
			}
		}

		// Singles with registryKey — emit typeof augmentation for each.
		// e.g., fields.ts with registryKey: "~fieldTypes" → "~fieldTypes": typeof _fields;
		//
		// SKIP ~-prefixed keys (e.g. "~fieldTypes") — these are emitted ONCE by the
		// root template to avoid merge conflicts when multiple modules augment the
		// same Registry property with different types (TypeScript degrades to `any`).
		const discoverPatterns = options.discoverPatterns ?? {};
		for (const [singleName, pattern] of Object.entries(discoverPatterns)) {
			if (typeof pattern !== "object" || !pattern.registryKey) continue;
			if (pattern.registryKey.startsWith("~")) continue;
			const singleFile = discovered.singles.get(singleName);
			if (!singleFile) continue;
			registryLines.push(`\t\t${safeKey(pattern.registryKey)}: typeof ${singleFile.varName};`);
		}

		if (registryLines.length > 0) {
			lines.push("// ════════════════════════════════════════════════════════════");
			lines.push("// Registry augmentation — module registries");
			lines.push("// ════════════════════════════════════════════════════════════");
			lines.push("");
			lines.push("declare global {");
			lines.push("\tnamespace Questpie {");
			lines.push("\t\tinterface Registry {");
			for (const line of registryLines) {
				lines.push(`\t${line}`);
			}
			lines.push("\t\t}");
			lines.push("\t}");
			lines.push("}");
			lines.push("");
		}
	}

	return lines.join("\n");
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Derive a PascalCase type prefix from a module name.
 * "questpie-admin" → "Admin"
 * "questpie-audit" → "Audit"
 * "billing" → "Billing"
 */
function deriveTypePrefix(moduleName: string): string {
	// Remove "questpie-" prefix if present
	const name = moduleName.replace(/^questpie-/, "");
	// Split on hyphens and PascalCase
	return name
		.split("-")
		.map((s) => s.charAt(0).toUpperCase() + s.slice(1))
		.join("");
}

/**
 * Get all singles except "modules" (which is handled separately).
 */
function getNonModuleSingles(
	singles: Map<string, DiscoveredFile>,
): DiscoveredFile[] {
	const result: DiscoveredFile[] = [];
	for (const [key, file] of singles) {
		if (key === "modules") continue;
		result.push(file);
	}
	return result.sort((a, b) => a.key.localeCompare(b.key));
}

/**
 * Emit a plain type interface for a module category (no sub-module extends).
 * Always emit named types to prevent TS7056 ("inferred type exceeds maximum
 * length") when collection builder types are deeply nested via .merge().set().
 */
function emitSimpleTypeInterface(
	lines: string[],
	typeName: string,
	fileMap: Map<string, DiscoveredFile>,
): void {
	lines.push(`export interface ${typeName} {`);
	for (const file of sortedValues(fileMap)) {
		lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
	}
	lines.push("}");
	lines.push("");
}

// ============================================================================
// Nested structure builder (for emit: "nested" categories)
// ============================================================================

type NestedNode =
	| { type: "leaf"; varName: string }
	| { type: "branch"; children: Map<string, NestedNode> };

/**
 * Build a nested tree from dot-separated keys.
 * Used for categories with `emit: "nested"` (e.g., functions).
 *
 * "admin.stats" → { admin: { stats: leaf } }
 * "getConfig" → { getConfig: leaf }
 */
function buildNestedStructure(
	files: Map<string, DiscoveredFile>,
): Map<string, NestedNode> {
	const root = new Map<string, NestedNode>();
	for (const file of files.values()) {
		const segments = file.key.split(".");
		let current = root;
		for (let i = 0; i < segments.length; i++) {
			const seg = segments[i];
			const isLast = i === segments.length - 1;
			if (isLast) {
				current.set(seg, { type: "leaf", varName: file.varName });
			} else {
				let node = current.get(seg);
				if (!node || node.type === "leaf") {
					node = { type: "branch", children: new Map() };
					current.set(seg, node);
				}
				current = (node as Extract<NestedNode, { type: "branch" }>).children;
			}
		}
	}
	return root;
}

function emitNestedObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: ${node.varName},`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedObject(lines, node.children, indent + 1);
			lines.push(`${tabs}},`);
		}
	}
}

function emitNestedTypeObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: typeof ${node.varName};`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedTypeObject(lines, node.children, indent + 1);
			lines.push(`${tabs}};`);
		}
	}
}

function sortedValues(map: Map<string, DiscoveredFile>): DiscoveredFile[] {
	return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
}

function importStatement(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	return `import ${file.varName} from "${file.importPath}";`;
}

function safeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return `"${key}"`;
}
