/**
 * Template Generation
 *
 * Generates the `.generated/index.ts` file content from discovered files.
 * The generated file:
 * 1. Imports the config and all discovered entities
 * 2. Calls createApp(config, entities) to create the app instance
 * 3. Exports the app and type aliases
 *
 * @see RFC §15.1 (Complete .generated/index.ts Example)
 */

import type { DiscoveryResult } from "./discover.js";
import type { DiscoveredFile } from "./types.js";

// ============================================================================
// Template generation
// ============================================================================

export interface TemplateOptions {
	/** Path to questpie.config.ts relative to .generated directory. */
	configImportPath: string;
	/** Discovery result with all found files. */
	discovered: DiscoveryResult;
	/** Additional imports from plugins. */
	extraImports?: Array<{ name: string; path: string }>;
	/** Additional type declarations from plugins. */
	extraTypeDeclarations?: string[];
	/** Additional runtime code from plugins. */
	extraRuntimeCode?: string[];
	/** Additional entity keys to pass to createApp (from plugins). */
	extraEntities?: Map<string, string>;
}

/**
 * Generate the .generated/index.ts file content.
 */
export function generateTemplate(options: TemplateOptions): string {
	const lines: string[] = [];
	const {
		configImportPath,
		discovered,
		extraImports,
		extraTypeDeclarations,
		extraRuntimeCode,
		extraEntities,
	} = options;

	// Header
	lines.push("/* eslint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push("// Regenerate with: questpie generate");
	lines.push("");

	// Import createApp
	lines.push('import { createApp } from "questpie";');
	lines.push("");

	// Import config
	lines.push("// ── Config ─────────────────────────────────────────────────");
	lines.push(`import _config from "${configImportPath}";`);
	lines.push("");

	// Import collections
	if (discovered.collections.size > 0) {
		lines.push(
			"// ── Collections ────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.collections)) {
			lines.push(`import ${file.varName} from "${file.importPath}";`);
		}
		lines.push("");
	}

	// Import globals
	if (discovered.globals.size > 0) {
		lines.push(
			"// ── Globals ────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.globals)) {
			lines.push(`import ${file.varName} from "${file.importPath}";`);
		}
		lines.push("");
	}

	// Import jobs
	if (discovered.jobs.size > 0) {
		lines.push(
			"// ── Jobs ───────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.jobs)) {
			lines.push(`import ${file.varName} from "${file.importPath}";`);
		}
		lines.push("");
	}

	// Import functions
	if (discovered.functions.size > 0) {
		lines.push(
			"// ── Functions ──────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.functions)) {
			lines.push(`import ${file.varName} from "${file.importPath}";`);
		}
		lines.push("");
	}

	// Import messages
	if (discovered.messages.size > 0) {
		lines.push(
			"// ── Messages ───────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.messages)) {
			lines.push(`import ${file.varName} from "${file.importPath}";`);
		}
		lines.push("");
	}

	// Import auth
	if (discovered.auth) {
		lines.push(
			"// ── Auth ───────────────────────────────────────────────────",
		);
		lines.push(
			`import ${discovered.auth.varName} from "${discovered.auth.importPath}";`,
		);
		lines.push("");
	}

	// Import custom (plugin-discovered files, e.g. blocks)
	for (const [stateKey, fileMap] of discovered.custom) {
		if (fileMap.size > 0) {
			const label = stateKey.charAt(0).toUpperCase() + stateKey.slice(1);
			lines.push(
				`// ── ${label} ──────────────────────────────────────────────`,
			);
			for (const file of sortedValues(fileMap)) {
				lines.push(`import ${file.varName} from "${file.importPath}";`);
			}
			lines.push("");
		}
	}

	// Extra plugin imports
	if (extraImports && extraImports.length > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const imp of extraImports) {
			lines.push(`import ${imp.name} from "${imp.path}";`);
		}
		lines.push("");
	}

	// Extra type declarations
	if (extraTypeDeclarations && extraTypeDeclarations.length > 0) {
		lines.push(
			"// ── Type Declarations ──────────────────────────────────────",
		);
		for (const decl of extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// Runtime: createApp
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// RUNTIME — create the app instance");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");
	lines.push("export const app = createApp(_config, {");

	// Collections
	if (discovered.collections.size > 0) {
		lines.push("\tcollections: {");
		for (const file of sortedValues(discovered.collections)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Globals
	if (discovered.globals.size > 0) {
		lines.push("\tglobals: {");
		for (const file of sortedValues(discovered.globals)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Jobs
	if (discovered.jobs.size > 0) {
		lines.push("\tjobs: {");
		for (const file of sortedValues(discovered.jobs)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Functions — build nested object from dot-separated keys
	if (discovered.functions.size > 0) {
		lines.push("\tfunctions: {");
		const nested = buildNestedFunctions(discovered.functions);
		emitNestedObject(lines, nested, 2);
		lines.push("\t},");
	}

	// Messages
	if (discovered.messages.size > 0) {
		lines.push("\tmessages: {");
		for (const file of sortedValues(discovered.messages)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Auth
	if (discovered.auth) {
		lines.push(`\tauth: ${discovered.auth.varName},`);
	}

	// Custom (plugin-discovered, e.g. blocks)
	for (const [stateKey, fileMap] of discovered.custom) {
		if (fileMap.size > 0) {
			lines.push(`\t${safeKey(stateKey)}: {`);
			for (const file of sortedValues(fileMap)) {
				lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
			}
			lines.push("\t},");
		}
	}

	// Extra entities from plugins
	if (extraEntities) {
		for (const [key, value] of extraEntities) {
			lines.push(`\t${safeKey(key)}: ${value},`);
		}
	}

	lines.push("});");
	lines.push("");

	// Type exports
	lines.push("export type App = typeof app;");
	lines.push('export type AppRpc = App["functions"];');
	lines.push("");

	// Extra runtime code from plugins
	if (extraRuntimeCode && extraRuntimeCode.length > 0) {
		for (const code of extraRuntimeCode) {
			lines.push(code);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ============================================================================
// Nested functions builder
// ============================================================================

type NestedNode =
	| { type: "leaf"; varName: string }
	| { type: "branch"; children: Map<string, NestedNode> };

/**
 * Build a nested tree from dot-separated function keys.
 * "search" → { search: leaf }
 * "admin.stats" → { admin: { stats: leaf } }
 */
function buildNestedFunctions(
	functions: Map<string, DiscoveredFile>,
): Map<string, NestedNode> {
	const root = new Map<string, NestedNode>();

	for (const file of functions.values()) {
		const segments = file.key.split(".");
		let current = root;

		for (let i = 0; i < segments.length; i++) {
			const seg = segments[i];
			const isLast = i === segments.length - 1;

			if (isLast) {
				current.set(seg, { type: "leaf", varName: file.varName });
			} else {
				let node = current.get(seg);
				if (!node || node.type === "leaf") {
					node = { type: "branch", children: new Map() };
					current.set(seg, node);
				}
				current = (node as Extract<NestedNode, { type: "branch" }>).children;
			}
		}
	}

	return root;
}

/**
 * Emit a nested object structure as code lines.
 */
function emitNestedObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: ${node.varName},`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedObject(lines, node.children, indent + 1);
			lines.push(`${tabs}},`);
		}
	}
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Sort discovered files by key for deterministic output.
 */
function sortedValues(map: Map<string, DiscoveredFile>): DiscoveredFile[] {
	return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
}

/**
 * Quote a key if it's not a valid identifier.
 */
function safeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return `"${key}"`;
}
