/**
 * Template Generation
 *
 * Generates the `.generated/index.ts` file content from discovered files.
 * The generated file:
 * 1. Imports the config and all discovered entities
 * 2. Emits type interfaces using typeof references (zero inference cost)
 * 3. Calls createApp(config, entities) to create the app instance
 * 4. Exports the app and composed App type
 *
 * @see RFC §15.1 (Complete .generated/index.ts Example)
 */

import type { DiscoveryResult } from "./discover.js";
import type { DiscoveredFile } from "./types.js";

// ============================================================================
// Template generation
// ============================================================================

export interface TemplateOptions {
	/** Path to questpie.config.ts relative to .generated directory. */
	configImportPath: string;
	/** Discovery result with all found files. */
	discovered: DiscoveryResult;
	/** Additional imports from plugins. */
	extraImports?: Array<{ name: string; path: string }>;
	/** Additional type declarations from plugins. */
	extraTypeDeclarations?: string[];
	/** Additional runtime code from plugins. */
	extraRuntimeCode?: string[];
	/** Additional entity keys to pass to createApp (from plugins). */
	extraEntities?: Map<string, string>;
}

/**
 * Generate the .generated/index.ts file content.
 */
export function generateTemplate(options: TemplateOptions): string {
	const lines: string[] = [];
	const {
		configImportPath,
		discovered,
		extraImports,
		extraTypeDeclarations,
		extraRuntimeCode,
		extraEntities,
	} = options;

	// Header
	lines.push("/* eslint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push("// Regenerate with: questpie generate");
	lines.push("");

	// Import createApp + Questpie + QuestpieConfig + module extraction types
	lines.push(
		'import { createApp, type Questpie, type QuestpieConfig, type ExtractModulesProperty } from "questpie";',
	);
	lines.push("");

	// Import config
	lines.push("// ── Config ─────────────────────────────────────────────────");
	lines.push(`import _config from "${configImportPath}";`);
	lines.push("");

	// Import collections
	if (discovered.collections.size > 0) {
		lines.push(
			"// ── Collections ────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.collections)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import globals
	if (discovered.globals.size > 0) {
		lines.push(
			"// ── Globals ────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.globals)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import jobs
	if (discovered.jobs.size > 0) {
		lines.push(
			"// ── Jobs ───────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.jobs)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import functions
	if (discovered.functions.size > 0) {
		lines.push(
			"// ── Functions ──────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.functions)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import messages
	if (discovered.messages.size > 0) {
		lines.push(
			"// ── Messages ───────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.messages)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import auth
	if (discovered.auth) {
		lines.push(
			"// ── Auth ───────────────────────────────────────────────────",
		);
		lines.push(importStatement(discovered.auth));
		lines.push("");
	}

	// Import custom (plugin-discovered files, e.g. blocks)
	for (const [stateKey, fileMap] of discovered.custom) {
		if (fileMap.size > 0) {
			const label = stateKey.charAt(0).toUpperCase() + stateKey.slice(1);
			lines.push(
				`// ── ${label} ──────────────────────────────────────────────`,
			);
			for (const file of sortedValues(fileMap)) {
				lines.push(importStatement(file));
			}
			lines.push("");
		}
	}

	// Extra plugin imports
	if (extraImports && extraImports.length > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const imp of extraImports) {
			lines.push(`import ${imp.name} from "${imp.path}";`);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// TYPES — composed from typeof references (zero inference cost)
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push(
		"// TYPES — composed from typeof references (zero inference cost)",
	);
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	// Module type extraction — auto-extracts types from config's modules array
	lines.push("// ── Module type extraction (automatic from config) ─────────");
	lines.push(
		'type _ModuleCollections = ExtractModulesProperty<typeof _config, "collections">;',
	);
	lines.push(
		'type _ModuleGlobals = ExtractModulesProperty<typeof _config, "globals">;',
	);
	lines.push(
		'type _ModuleJobs = ExtractModulesProperty<typeof _config, "jobs">;',
	);
	lines.push(
		'type _ModuleFunctions = ExtractModulesProperty<typeof _config, "functions">;',
	);
	// Also extract custom keys (blocks, etc.) from modules
	for (const [stateKey] of discovered.custom) {
		const moduleTypeName = `_Module${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
		lines.push(
			`type ${moduleTypeName} = ExtractModulesProperty<typeof _config, "${stateKey}">;`,
		);
	}
	lines.push("");

	// AppCollections — module contributions + user overrides
	{
		const hasUser = discovered.collections.size > 0;
		lines.push(
			"/** All collections in the app (modules + user, user overrides) */",
		);
		if (hasUser) {
			lines.push(
				"export interface AppCollections extends _ModuleCollections {",
			);
			for (const file of sortedValues(discovered.collections)) {
				lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
			}
			lines.push("}");
		} else {
			lines.push("export type AppCollections = _ModuleCollections;");
		}
		lines.push("");
	}

	// AppGlobals — module contributions + user overrides
	{
		const hasUser = discovered.globals.size > 0;
		lines.push(
			"/** All globals in the app (modules + user, user overrides) */",
		);
		if (hasUser) {
			lines.push("export interface AppGlobals extends _ModuleGlobals {");
			for (const file of sortedValues(discovered.globals)) {
				lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
			}
			lines.push("}");
		} else {
			lines.push("export type AppGlobals = _ModuleGlobals;");
		}
		lines.push("");
	}

	// AppJobs — module contributions + user overrides
	{
		const hasUser = discovered.jobs.size > 0;
		lines.push("/** All jobs in the app (modules + user, user overrides) */");
		if (hasUser) {
			lines.push("export interface AppJobs extends _ModuleJobs {");
			for (const file of sortedValues(discovered.jobs)) {
				lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
			}
			lines.push("}");
		} else {
			lines.push("export type AppJobs = _ModuleJobs;");
		}
		lines.push("");
	}

	// AppFunctions — module contributions + user overrides (nested from directory layout)
	{
		const hasUser = discovered.functions.size > 0;
		lines.push(
			"/** All functions in the app (modules + user, user overrides) */",
		);
		if (hasUser) {
			lines.push("export interface AppFunctions extends _ModuleFunctions {");
			const nested = buildNestedFunctions(discovered.functions);
			emitNestedTypeObject(lines, nested, 1);
			lines.push("}");
		} else {
			lines.push("export type AppFunctions = _ModuleFunctions;");
		}
		lines.push("");
	}

	// AppBlocks and other custom plugin types — module contributions + user overrides
	for (const [stateKey, fileMap] of discovered.custom) {
		const typeName = `App${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
		const moduleTypeName = `_Module${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
		const hasUser = fileMap.size > 0;
		lines.push(
			`/** All ${stateKey} in the app (modules + user, user overrides) */`,
		);
		if (hasUser) {
			lines.push(`export interface ${typeName} extends ${moduleTypeName} {`);
			for (const file of sortedValues(fileMap)) {
				lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
			}
			lines.push("}");
		} else {
			lines.push(`export type ${typeName} = ${moduleTypeName};`);
		}
		lines.push("");
	}

	// AppMessageKeys
	if (discovered.messages.size > 0) {
		lines.push("/** Message keys — union of all keys from all locales */");
		const msgParts = sortedValues(discovered.messages).map(
			(f) => `keyof typeof ${f.varName}`,
		);
		lines.push(`export type AppMessageKeys = ${msgParts.join(" | ")};`);
		lines.push("");
	}

	// Extra type declarations from plugins
	if (extraTypeDeclarations && extraTypeDeclarations.length > 0) {
		for (const decl of extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// App type — composed Questpie<QuestpieConfig & {...}>
	lines.push("/** The fully typed Questpie app */");
	const stateMembers: string[] = [];
	// Always include these — they merge module + user contributions
	stateMembers.push("\tcollections: AppCollections;");
	stateMembers.push("\tglobals: AppGlobals;");
	stateMembers.push("\tjobs: AppJobs;");
	stateMembers.push("\tfunctions: AppFunctions;");
	for (const [stateKey] of discovered.custom) {
		const typeName = `App${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
		stateMembers.push(`\t${stateKey}: ${typeName};`);
	}
	if (discovered.messages.size > 0)
		stateMembers.push('\t"~messageKeys": AppMessageKeys;');

	lines.push("export type App = Questpie<QuestpieConfig & {");
	for (const member of stateMembers) {
		lines.push(member);
	}
	lines.push("}>;");
	lines.push("");

	// ════════════════════════════════════════════════════════════
	// RUNTIME — create the app instance
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// RUNTIME — create the app instance");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");
	lines.push("export const app: App = createApp(_config, {");

	// Collections
	if (discovered.collections.size > 0) {
		lines.push("\tcollections: {");
		for (const file of sortedValues(discovered.collections)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Globals
	if (discovered.globals.size > 0) {
		lines.push("\tglobals: {");
		for (const file of sortedValues(discovered.globals)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Jobs
	if (discovered.jobs.size > 0) {
		lines.push("\tjobs: {");
		for (const file of sortedValues(discovered.jobs)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Functions — build nested object from dot-separated keys
	if (discovered.functions.size > 0) {
		lines.push("\tfunctions: {");
		const nested = buildNestedFunctions(discovered.functions);
		emitNestedObject(lines, nested, 2);
		lines.push("\t},");
	}

	// Messages
	if (discovered.messages.size > 0) {
		lines.push("\tmessages: {");
		for (const file of sortedValues(discovered.messages)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Auth
	if (discovered.auth) {
		lines.push(`\tauth: ${discovered.auth.varName},`);
	}

	// Custom (plugin-discovered, e.g. blocks)
	for (const [stateKey, fileMap] of discovered.custom) {
		if (fileMap.size > 0) {
			lines.push(`\t${safeKey(stateKey)}: {`);
			for (const file of sortedValues(fileMap)) {
				lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
			}
			lines.push("\t},");
		}
	}

	// Extra entities from plugins
	if (extraEntities) {
		for (const [key, value] of extraEntities) {
			lines.push(`\t${safeKey(key)}: ${value},`);
		}
	}

	lines.push("}) as unknown as App;");
	lines.push("");

	// Extra runtime code from plugins
	if (extraRuntimeCode && extraRuntimeCode.length > 0) {
		for (const code of extraRuntimeCode) {
			lines.push(code);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ============================================================================
// Nested functions builder
// ============================================================================

type NestedNode =
	| { type: "leaf"; varName: string }
	| { type: "branch"; children: Map<string, NestedNode> };

/**
 * Build a nested tree from dot-separated function keys.
 * "search" → { search: leaf }
 * "admin.stats" → { admin: { stats: leaf } }
 */
function buildNestedFunctions(
	functions: Map<string, DiscoveredFile>,
): Map<string, NestedNode> {
	const root = new Map<string, NestedNode>();

	for (const file of functions.values()) {
		const segments = file.key.split(".");
		let current = root;

		for (let i = 0; i < segments.length; i++) {
			const seg = segments[i];
			const isLast = i === segments.length - 1;

			if (isLast) {
				current.set(seg, { type: "leaf", varName: file.varName });
			} else {
				let node = current.get(seg);
				if (!node || node.type === "leaf") {
					node = { type: "branch", children: new Map() };
					current.set(seg, node);
				}
				current = (node as Extract<NestedNode, { type: "branch" }>).children;
			}
		}
	}

	return root;
}

/**
 * Emit a nested object structure as runtime code lines.
 */
function emitNestedObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: ${node.varName},`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedObject(lines, node.children, indent + 1);
			lines.push(`${tabs}},`);
		}
	}
}

/**
 * Emit a nested type structure for interface declarations.
 */
function emitNestedTypeObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: typeof ${node.varName};`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedTypeObject(lines, node.children, indent + 1);
			lines.push(`${tabs}};`);
		}
	}
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Sort discovered files by key for deterministic output.
 */
function sortedValues(map: Map<string, DiscoveredFile>): DiscoveredFile[] {
	return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
}

/**
 * Generate the import statement for a discovered file.
 * Uses default import for "default" exports, named import for "named" exports.
 */
function importStatement(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	// default or unknown — use default import
	return `import ${file.varName} from "${file.importPath}";`;
}

/**
 * Quote a key if it's not a valid identifier.
 */
function safeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return `"${key}"`;
}
