/**
 * Registry Helper Functions
 *
 * Standalone definition factories for views and components.
 * Used by admin module internals and exported for user-facing definitions.
 *
 * @example
 * ```ts
 * import { view, component } from "@questpie/admin/server";
 *
 * // In views/kanban.ts (file convention)
 * export default view("kanban", {
 *   kind: "list",
 *   configSchema: z.object({ groupBy: z.string() }),
 * });
 *
 * // In components/rating.ts (file convention)
 * export default component("rating", {
 *   propsSchema: z.object({ value: z.number(), max: z.number().default(5) }),
 * });
 *
 * // In a module definition
 * module({
 *   views: { table: view("table", { kind: "list" }) },
 *   components: { icon: component("icon") },
 * });
 * ```
 */

import type {
	ComponentDefinition,
	EditViewDefinition,
	ListViewDefinition,
	ViewDefinition,
	ViewKind,
} from "./augmentation.js";

// ============================================================================
// View Factory
// ============================================================================

/**
 * Create a view definition with a `kind` discriminant and typed config.
 *
 * `kind` determines which registry this view belongs to:
 * - `"list"` → used in `.list()` callback via `v.myView()`
 * - `"form"` → used in `.form()` callback via `v.myView()`
 *
 * The first generic parameter `TConfig` carries the config type that
 * `v.myView(config)` will accept in `.list()` / `.form()` callbacks.
 * When omitted, the view accepts `unknown` (no type checking on config).
 *
 * The `kind` field is plugin-extensible — plugins can register new view kinds
 * via the `ViewKindRegistry` augmentation interface.
 *
 * @example
 * ```ts
 * // views/table.ts — built-in list view with typed config
 * export default view<ListViewConfig>("table", { kind: "list" });
 *
 * // views/kanban.ts — custom list view with its own config type
 * interface KanbanConfig { groupBy: string; swimlanes?: boolean }
 * export default view<KanbanConfig>("kanban", { kind: "list" });
 *
 * // views/wizard.ts — custom edit view
 * interface WizardConfig { steps: { title: string; fields: string[] }[] }
 * export default view<WizardConfig>("wizard", { kind: "form" });
 * ```
 */
export function view<
	TConfig = unknown,
	TName extends string = string,
	TKind extends ViewKind = ViewKind,
>(
	name: TName,
	config: { kind: TKind } & Record<string, unknown>,
): ViewDefinition<TName, TKind, TConfig> {
	return { type: "view", name, ...config } as ViewDefinition<
		TName,
		TKind,
		TConfig
	>;
}

// ============================================================================
// Legacy View Factories (aliases for backward compatibility)
// ============================================================================

/**
 * Create a list view definition.
 * @deprecated Use `view(name, { kind: "list", ... })` instead.
 */
export function listView<TName extends string>(
	name: TName,
	config: Record<string, unknown> = {},
): ListViewDefinition<TName> {
	return { type: "listView", name, ...config };
}

/**
 * Create an edit view definition.
 * @deprecated Use `view(name, { kind: "form", ... })` instead.
 */
export function editView<TName extends string>(
	name: TName,
	config: Record<string, unknown> = {},
): EditViewDefinition<TName> {
	return { type: "editView", name, ...config };
}

// ============================================================================
// Component Factory
// ============================================================================

/**
 * Create a component definition with typed props.
 *
 * The first generic parameter `TProps` carries the input props type that
 * `c.myComponent(props)` will accept in `.admin()` callbacks.
 * When omitted, the component accepts `Record<string, unknown> | string`.
 *
 * @example
 * ```ts
 * // components/icon.ts — string shorthand for icon name
 * export default component<string | { name: string }>("icon");
 *
 * // components/rating.ts — typed props
 * interface RatingProps { value: number; max?: number }
 * export default component<RatingProps>("rating");
 * ```
 */
export function component<TProps = unknown, TName extends string = string>(
	name: TName,
	config: Record<string, unknown> = {},
): ComponentDefinition<TName, TProps> {
	return { type: "component", name, ...config } as ComponentDefinition<
		TName,
		TProps
	>;
}

// ============================================================================
// View Filtering (for codegen-generated listViews/formViews)
// ============================================================================

/**
 * Filter a views record by kind, returning only views matching the specified kind.
 *
 * Used by codegen to derive `listViews`/`formViews` from the unified `views` category.
 * Each view file defines `view("name", { kind: "list"|"form" })`. This function
 * filters at module-definition time so the module exports separate registries.
 *
 * @example
 * ```ts
 * // Generated by codegen in .generated/module.ts:
 * listViews: filterViewsByKind({ table: _view_table, form: _view_form }, "list"),
 * formViews: filterViewsByKind({ table: _view_table, form: _view_form }, "form"),
 * ```
 */
export function filterViewsByKind<
	TViews extends Record<string, ViewDefinition<string, ViewKind, any>>,
	TKind extends ViewKind,
>(
	views: TViews,
	kind: TKind,
): {
	[K in keyof TViews as TViews[K] extends { kind: TKind }
		? K
		: never]: TViews[K];
} {
	const result: Record<string, ViewDefinition<string, ViewKind, any>> = {};
	for (const [key, view] of Object.entries(views)) {
		if (view.kind === kind) {
			result[key] = view;
		}
	}
	return result as any;
}
