/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Typed factory functions with plugin extensions. Regenerate with: questpie generate

// ── Core Imports ───────────────────────────────────────────
import { CollectionBuilder, GlobalBuilder, wrapBuilderWithExtensions, type EmptyCollectionState, type EmptyGlobalState } from "questpie";

// ── Module import (for type extraction) ──
import _modulesArr from "../modules";

// ── Plugin Imports ─────────────────────────────────────────
import { type LocaleConfig, type GlobalHooksInput, type CollectionAccess, type ContextResolver } from "questpie";

// ════════════════════════════════════════════════════════════
// Type extraction from Registry — driven by CategoryDeclaration
// ════════════════════════════════════════════════════════════

type _RegistryProp<K extends string> = Registry extends Record<K, infer V> ? V : Record<string, unknown>;


// Field types — extracted from modules
import type { ExtractModuleProp } from "questpie";
type _AllFieldTypes = ExtractModuleProp<{ modules: typeof _modulesArr }, "fields">;

// ════════════════════════════════════════════════════════════
// Type augmentations — generated from plugin registries
// ════════════════════════════════════════════════════════════

declare global {
	namespace Questpie {
		interface FieldTypeRegistry extends Record<keyof _AllFieldTypes, {}> { }
	}
}

// ════════════════════════════════════════════════════════════
// Extension registries
// ════════════════════════════════════════════════════════════

// ════════════════════════════════════════════════════════════
// Factory functions
// ════════════════════════════════════════════════════════════

// ════════════════════════════════════════════════════════════
// Singleton factory functions
// ════════════════════════════════════════════════════════════

/** Typed factory for locale config. */
export function locale<T extends LocaleConfig>(config: T): T { return config; }

/** Typed factory for hooks config. */
export function hooks<T extends GlobalHooksInput>(config: T): T { return config; }

/** Typed factory for access config. */
export function access<T extends CollectionAccess>(config: T): T { return config; }

/** Typed factory for context config. */
export function context<T extends ContextResolver>(config: T): T { return config; }
