/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Typed factory functions with plugin extensions. Regenerate with: questpie generate

// ── Core Imports ───────────────────────────────────────────
import { CollectionBuilder, GlobalBuilder, type EmptyCollectionState, type EmptyGlobalState } from "questpie";

// ── Module import (for type extraction + runtime fields) ──
import _modulesArr from "../modules";

// ── Plugin Imports ─────────────────────────────────────────
import { type LocaleConfig, type GlobalHooksInput, type CollectionAccess, type ContextResolver } from "questpie";
import { type AdminCollectionConfig, type AdminConfigContext, type ListViewConfig, type ListViewConfigContext, type FormViewConfig, type FormViewConfigContext, type PreviewConfig, type ServerActionsConfig, type ActionsConfigContext, type AdminGlobalConfig, type ServerBrandingConfig, type AdminLocaleConfig, type SidebarContribution, type DashboardContribution, createComponentProxy, createViewProxy, createFieldProxy, createActionProxy } from "@questpie/admin/server";

// ════════════════════════════════════════════════════════════
// Module type extraction — views, components, field types (all from modules)
// ════════════════════════════════════════════════════════════

type _FlattenModules<T> = T extends readonly (infer M)[]
  ? M | (M extends { modules: infer Sub } ? _FlattenModules<Sub> : never)
  : never;
type _AllModules = _FlattenModules<typeof _modulesArr>;

// Module registry names — extracted from module registrations
type _ExtractKeys<K extends string> = _AllModules extends infer M ? M extends Record<K, Record<infer V extends string, any>> ? V : never : never;
type _ViewsNames = _ExtractKeys<"views"> | (string & {});
type _ListViewsNames = _ExtractKeys<"listViews"> | (string & {});
type _EditViewsNames = _ExtractKeys<"editViews"> | (string & {});
type _ComponentsNames = _ExtractKeys<"components"> | (string & {});
type _ComponentsNames_Strict = _ExtractKeys<"components">;

// Field types — all field types come from modules (starter, admin, etc.)
type _U2I<U> = (U extends any ? (x: U) => void : never) extends (x: infer I) => void ? I : never;
type _ModuleFieldTypes = _U2I<_AllModules extends infer M ? M extends { fields: infer F } ? F : never : never>;
type _AllFieldTypes = [_ModuleFieldTypes] extends [never] ? Record<string, never> : _ModuleFieldTypes;

// ── Runtime: extract fields from modules ────────────────────
function _extractModuleFields(modules: readonly any[]): Record<string, any> {
	const merged: Record<string, any> = {};
	for (const m of modules) {
		if (m.fields) Object.assign(merged, m.fields);
		if (m.modules) Object.assign(merged, _extractModuleFields(m.modules));
	}
	return merged;
}
const _allRuntimeFields = _extractModuleFields(_modulesArr);

// ════════════════════════════════════════════════════════════
// Type augmentations — generated from plugin registries
// ════════════════════════════════════════════════════════════

declare module "questpie" {
	interface CollectionBuilder<TState> {
		admin(configFn: AdminCollectionConfig | ((ctx: AdminConfigContext<_ComponentsNames>) => AdminCollectionConfig)): CollectionBuilder<TState>;
		list(configFn: (ctx: ListViewConfigContext<TState extends { fieldDefinitions: infer F extends Record<string, any> } ? F : Record<string, any>, _ListViewsNames>) => ListViewConfig): CollectionBuilder<TState>;
		form(configFn: (ctx: FormViewConfigContext<TState extends { fieldDefinitions: infer F extends Record<string, any> } ? F : Record<string, any>, _EditViewsNames>) => FormViewConfig): CollectionBuilder<TState>;
		preview(config: PreviewConfig): CollectionBuilder<TState>;
		actions(configFn: (ctx: ActionsConfigContext<Record<string, unknown>, _ComponentsNames>) => ServerActionsConfig): CollectionBuilder<TState>;
	}
	interface GlobalBuilder<TState> {
		admin(configFn: AdminGlobalConfig | ((ctx: AdminConfigContext<_ComponentsNames>) => AdminGlobalConfig)): GlobalBuilder<TState>;
		form(configFn: (ctx: FormViewConfigContext<TState extends { fieldDefinitions: infer F extends Record<string, any> } ? F : Record<string, any>, _EditViewsNames>) => FormViewConfig): GlobalBuilder<TState>;
	}
	interface Registry {
		views: Record<_ViewsNames, unknown>;
		listViews: Record<_ListViewsNames, unknown>;
		editViews: Record<_EditViewsNames, unknown>;
		components: Record<_ComponentsNames, unknown>;
	}
	interface FieldTypeRegistry extends Record<keyof _AllFieldTypes, {}> {}
}

declare module "@questpie/admin/server" {
	interface ComponentTypeRegistry extends Record<_ComponentsNames_Strict, {}> {}
}

// ════════════════════════════════════════════════════════════
// Extension registries + Proxy wrappers
// ════════════════════════════════════════════════════════════

const _collExt: Record<string, { stateKey: string; resolve: (v: any) => any }> = {
	admin: {
		stateKey: "admin",
		resolve(configOrFn: any) {
			if (typeof configOrFn === 'function') return configOrFn({ c: new Proxy({}, { get: (_, prop) => (...args: any[]) => ({ type: String(prop), props: typeof args[0] === "string" ? { name: args[0] } : args[0] ?? {} }) }) });
			return configOrFn;
		},
	},
	list: {
		stateKey: "adminList",
		resolve(configOrFn: any) {
			if (typeof configOrFn === 'function') return configOrFn({ v: new Proxy({}, { get: (_, prop) => (config: any) => ({ view: String(prop), ...config }) }), f: new Proxy({}, { get: (_, prop) => String(prop) }), a: new Proxy({ custom: (name: string, config: any) => ({ id: name, ...config }) }, { get: (target, prop) => (target as any)[prop] ?? String(prop) }) });
			return configOrFn;
		},
	},
	form: {
		stateKey: "adminForm",
		resolve(configOrFn: any) {
			if (typeof configOrFn === 'function') return configOrFn({ v: new Proxy({}, { get: (_, prop) => (config: any) => ({ view: String(prop), ...config }) }), f: new Proxy({}, { get: (_, prop) => String(prop) }) });
			return configOrFn;
		},
	},
	preview: { stateKey: "adminPreview", resolve: (v: any) => v },
	actions: {
		stateKey: "adminActions",
		resolve(configOrFn: any) {
			if (typeof configOrFn === 'function') return configOrFn({ a: new Proxy({ custom: (name: string, config: any) => ({ id: name, ...config }) }, { get: (target, prop) => (target as any)[prop] ?? String(prop) }), c: new Proxy({}, { get: (_, prop) => (...args: any[]) => ({ type: String(prop), props: typeof args[0] === "string" ? { name: args[0] } : args[0] ?? {} }) }), f: new Proxy({}, { get: (_, prop) => String(prop) }) });
			return configOrFn;
		},
	},
};

function _wrapColl(builder: any): any {
	return new Proxy(builder, {
		get(target, prop, receiver) {
			if (typeof prop === 'string' && prop in _collExt) {
				const ext = _collExt[prop];
				return (configOrFn: any) => _wrapColl(target.set(ext.stateKey, ext.resolve(configOrFn)));
			}
			const val = Reflect.get(target, prop, receiver);
			if (typeof val === 'function') {
				return function(this: any, ...args: any[]) {
					const result = val.apply(target, args);
					return result instanceof CollectionBuilder ? _wrapColl(result) : result;
				};
			}
			return val;
		},
	});
}

const _globExt: Record<string, { stateKey: string; resolve: (v: any) => any }> = {
	admin: {
		stateKey: "admin",
		resolve(configOrFn: any) {
			if (typeof configOrFn === 'function') return configOrFn({ c: new Proxy({}, { get: (_, prop) => (...args: any[]) => ({ type: String(prop), props: typeof args[0] === "string" ? { name: args[0] } : args[0] ?? {} }) }) });
			return configOrFn;
		},
	},
	form: {
		stateKey: "adminForm",
		resolve(configOrFn: any) {
			if (typeof configOrFn === 'function') return configOrFn({ v: new Proxy({}, { get: (_, prop) => (config: any) => ({ view: String(prop), ...config }) }), f: new Proxy({}, { get: (_, prop) => String(prop) }) });
			return configOrFn;
		},
	},
};

function _wrapGlob(builder: any): any {
	return new Proxy(builder, {
		get(target, prop, receiver) {
			if (typeof prop === 'string' && prop in _globExt) {
				const ext = _globExt[prop];
				return (configOrFn: any) => _wrapGlob(target.set(ext.stateKey, ext.resolve(configOrFn)));
			}
			const val = Reflect.get(target, prop, receiver);
			if (typeof val === 'function') {
				return function(this: any, ...args: any[]) {
					const result = val.apply(target, args);
					return result instanceof GlobalBuilder ? _wrapGlob(result) : result;
				};
			}
			return val;
		},
	});
}

// ════════════════════════════════════════════════════════════
// Factory functions
// ════════════════════════════════════════════════════════════

/**
 * Create a typed collection builder with plugin extensions.
 *
 * @example
 * ```ts
 * import { collection } from "#questpie";
 *
 * export default collection("posts")
 *   .fields(({ f }) => ({ title: f.text({ required: true }) }))
 *   .admin(({ c }) => ({ icon: c.icon("ph:article") }))
 *   .list(({ v, f }) => v.table({ columns: [f.title] }))
 * ```
 */
export function collection<TName extends string>(name: TName): CollectionBuilder<EmptyCollectionState<TName, undefined, _AllFieldTypes>> {
	return _wrapColl(new CollectionBuilder({
		name: name as string,
		fields: {},
		localized: [],
		virtuals: undefined,
		relations: {},
		indexes: {},
		title: undefined,
		options: {},
		hooks: {},
		access: {},
		searchable: undefined,
		validation: undefined,
		output: undefined,
		upload: undefined,
		fieldDefinitions: {},
		"~questpieApp": { state: { fields: _allRuntimeFields } },
	})) as any;
}

/**
 * Create a typed global builder with plugin extensions.
 */
export function global<TName extends string>(name: TName): GlobalBuilder<EmptyGlobalState<TName, undefined, _AllFieldTypes>> {
	return _wrapGlob(new GlobalBuilder({
		name: name as string,
		fields: {},
		localized: [],
		virtuals: {},
		relations: {},
		options: {},
		hooks: {},
		access: {},
		fieldDefinitions: {},
		"~questpieApp": { state: { fields: _allRuntimeFields } },
	})) as any;
}

// ════════════════════════════════════════════════════════════
// Singleton factory functions
// ════════════════════════════════════════════════════════════

/** Typed factory for locale config. */
export function locale<T extends LocaleConfig>(config: T): T { return config; }

/** Typed factory for hooks config. */
export function hooks<T extends GlobalHooksInput>(config: T): T { return config; }

/** Typed factory for access config. */
export function access<T extends CollectionAccess>(config: T): T { return config; }

/** Typed factory for context config. */
export function context<T extends ContextResolver>(config: T): T { return config; }

/** Typed factory for branding config. */
export function branding<T extends ServerBrandingConfig>(config: T): T { return config; }

/** Typed factory for adminLocale config. */
export function adminLocale<T extends AdminLocaleConfig>(config: T): T { return config; }

/** Typed factory for sidebar config. Accepts plain config or callback. */
export function sidebar<T extends SidebarContribution>(config: T): T;
export function sidebar<T extends (...args: any[]) => SidebarContribution>(cb: T): T;
export function sidebar(v: any): any { return v; }

/** Typed factory for dashboard config. Accepts plain config or callback. */
export function dashboard<T extends DashboardContribution>(config: T): T;
export function dashboard<T extends (...args: any[]) => DashboardContribution>(cb: T): T;
export function dashboard(v: any): any { return v; }
