/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Typed factory functions with plugin extensions. Regenerate with: questpie generate

// ── Core Imports ───────────────────────────────────────────
import { CollectionBuilder, GlobalBuilder, type EmptyCollectionState, type EmptyGlobalState, type Registry } from "questpie";

// ── Module import (for runtime fields) ──
import _modulesArr from "../modules";

// ── Plugin Imports ─────────────────────────────────────────
import { type LocaleConfig, type GlobalHooksInput, type CollectionAccess, type ContextResolver } from "questpie";

// ════════════════════════════════════════════════════════════
// Type extraction from Registry — driven by CategoryDeclaration
// ════════════════════════════════════════════════════════════

type _RegistryProp<K extends string> = Registry extends Record<K, infer V> ? V : Record<string, unknown>;


// Field types — extracted from modules
type _ExtractProp<M, K extends string> = (M extends { modules: infer Sub extends readonly any[] } ? _ExtractPropArr<Sub, K> : {}) & (K extends keyof M ? M[K] extends Record<string, any> ? M[K] : {} : {});
type _ExtractPropArr<A extends readonly any[], K extends string> = A extends readonly [infer H, ...infer T extends readonly any[]] ? _ExtractProp<H, K> & _ExtractPropArr<T, K> : {};
type _AllFieldTypes = _ExtractProp<{ modules: typeof _modulesArr }, "fields">;

// ── Runtime: extract fields from modules ────────────────────
function _extractModuleFields(modules: readonly any[]): Record<string, any> {
	const merged: Record<string, any> = {};
	for (const m of modules) {
		if (m.fields) Object.assign(merged, m.fields);
		if (m.modules) Object.assign(merged, _extractModuleFields(m.modules));
	}
	return merged;
}
const _allRuntimeFields = _extractModuleFields(_modulesArr);

// ════════════════════════════════════════════════════════════
// Type augmentations — generated from plugin registries
// ════════════════════════════════════════════════════════════

declare global {
	namespace Questpie {
		interface FieldTypeRegistry extends Record<keyof _AllFieldTypes, {}> {}
	}
}

// ════════════════════════════════════════════════════════════
// Extension registries + Proxy wrappers
// ════════════════════════════════════════════════════════════

// ════════════════════════════════════════════════════════════
// Factory functions
// ════════════════════════════════════════════════════════════

// ════════════════════════════════════════════════════════════
// Singleton factory functions
// ════════════════════════════════════════════════════════════

/** Typed factory for locale config. */
export function locale<T extends LocaleConfig>(config: T): T { return config; }

/** Typed factory for hooks config. */
export function hooks<T extends GlobalHooksInput>(config: T): T { return config; }

/** Typed factory for access config. */
export function access<T extends CollectionAccess>(config: T): T { return config; }

/** Typed factory for context config. */
export function context<T extends ContextResolver>(config: T): T { return config; }
