/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import {
	createApp,
	type ExtractModulesProperty,
	type Questpie,
	type QuestpieConfig,
} from "questpie";
// ── Auth ───────────────────────────────────────────────────
import _auth from "../auth";
// ── Blocks ─────────────────────────────────────────────────
import {
	accordionBlock as _bloc_accordion,
	announcementBannerBlock as _bloc_announcementBanner,
	columnsBlock as _bloc_columns,
	contactsListBlock as _bloc_contactsList,
	ctaBlock as _bloc_cta,
	dividerBlock as _bloc_divider,
	documentsListBlock as _bloc_documentsList,
	galleryBlock as _bloc_gallery,
	headingBlock as _bloc_heading,
	heroBlock as _bloc_hero,
	imageBlock as _bloc_image,
	imageTextBlock as _bloc_imageText,
	latestNewsBlock as _bloc_latestNews,
	spacerBlock as _bloc_spacer,
	textBlock as _bloc_text,
	videoBlock as _bloc_video,
} from "../blocks";
// ── Collections ────────────────────────────────────────────
import _coll_announcements from "../collections/announcements";
import _coll_cities from "../collections/cities";
import _coll_cityMembers from "../collections/city-members";
import _coll_contacts from "../collections/contacts";
import _coll_documents from "../collections/documents";
import _coll_news from "../collections/news";
import _coll_pages from "../collections/pages";
import _coll_submissions from "../collections/submissions";
// ── Globals ────────────────────────────────────────────────
import _glob_siteSettings from "../globals/site-settings";
// ── Config ─────────────────────────────────────────────────
import _config from "../questpie.config";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

// ── Module type extraction (automatic from config) ─────────
type _ModuleCollections = ExtractModulesProperty<typeof _config, "collections">;
type _ModuleGlobals = ExtractModulesProperty<typeof _config, "globals">;
type _ModuleJobs = ExtractModulesProperty<typeof _config, "jobs">;
type _ModuleFunctions = ExtractModulesProperty<typeof _config, "functions">;
type _ModuleBlocks = ExtractModulesProperty<typeof _config, "blocks">;

/** All collections in the app (modules + user, user overrides) */
export interface AppCollections extends _ModuleCollections {
	announcements: typeof _coll_announcements;
	cities: typeof _coll_cities;
	cityMembers: typeof _coll_cityMembers;
	contacts: typeof _coll_contacts;
	documents: typeof _coll_documents;
	news: typeof _coll_news;
	pages: typeof _coll_pages;
	submissions: typeof _coll_submissions;
}

/** All globals in the app (modules + user, user overrides) */
export interface AppGlobals extends _ModuleGlobals {
	siteSettings: typeof _glob_siteSettings;
}

/** All jobs in the app (modules + user, user overrides) */
export interface AppJobs extends _ModuleJobs {}

/** All functions in the app (modules + user, user overrides) */
export interface AppFunctions extends _ModuleFunctions {}

/** All blocks in the app (modules + user, user overrides) */
export interface AppBlocks extends _ModuleBlocks {
	hero: typeof _bloc_hero;
	cta: typeof _bloc_cta;
	announcementBanner: typeof _bloc_announcementBanner;
	text: typeof _bloc_text;
	heading: typeof _bloc_heading;
	image: typeof _bloc_image;
	gallery: typeof _bloc_gallery;
	imageText: typeof _bloc_imageText;
	video: typeof _bloc_video;
	accordion: typeof _bloc_accordion;
	latestNews: typeof _bloc_latestNews;
	contactsList: typeof _bloc_contactsList;
	documentsList: typeof _bloc_documentsList;
	columns: typeof _bloc_columns;
	spacer: typeof _bloc_spacer;
	divider: typeof _bloc_divider;
}

/** The fully typed Questpie app */
export type App = Questpie<
	QuestpieConfig & {
		collections: AppCollections;
		globals: AppGlobals;
		jobs: AppJobs;
		functions: AppFunctions;
		blocks: AppBlocks;
	}
>;

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

export const app: App = createApp(_config, {
	collections: {
		announcements: _coll_announcements,
		cities: _coll_cities,
		cityMembers: _coll_cityMembers,
		contacts: _coll_contacts,
		documents: _coll_documents,
		news: _coll_news,
		pages: _coll_pages,
		submissions: _coll_submissions,
	},
	globals: {
		siteSettings: _glob_siteSettings,
	},
	auth: _auth,
	blocks: {
		hero: _bloc_hero,
		cta: _bloc_cta,
		announcementBanner: _bloc_announcementBanner,
		text: _bloc_text,
		heading: _bloc_heading,
		image: _bloc_image,
		gallery: _bloc_gallery,
		imageText: _bloc_imageText,
		video: _bloc_video,
		accordion: _bloc_accordion,
		latestNews: _bloc_latestNews,
		contactsList: _bloc_contactsList,
		documentsList: _bloc_documentsList,
		columns: _bloc_columns,
		spacer: _bloc_spacer,
		divider: _bloc_divider,
	},
}) as unknown as App;
