/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Sub-Modules ────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_account from "../collections/account";
import _coll_admin_locks from "../collections/admin-locks";
import _coll_admin_preferences from "../collections/admin-preferences";
import _coll_admin_saved_views from "../collections/admin-saved-views";
import _coll_apikey from "../collections/apikey";
import _coll_assets from "../collections/assets";
import _coll_session from "../collections/session";
import _coll_user from "../collections/user";
import _coll_verification from "../collections/verification";

// ── Functions ────────────────────────────────────────────
import { adminConfigFunctions as _fn_adminConfig } from "../functions/admin-config";
import { actionFunctions as _fn_executeAction } from "../functions/execute-action";
import { localeFunctions as _fn_locales } from "../functions/locales";
import { previewFunctions as _fn_preview } from "../functions/preview";
import { reactiveFunctions as _fn_reactive } from "../functions/reactive";
import { setupFunctions as _fn_setup } from "../functions/setup";
import { translationFunctions as _fn_translations } from "../functions/translations";
import { widgetDataFunctions as _fn_widgetData } from "../functions/widget-data";

// ── Views ────────────────────────────────────────────
import _view_collectionForm from "../views/form";
import _view_collectionTable from "../views/table";
import _view_globalForm from "../views/global-form";

// ── Components ────────────────────────────────────────────
import _comp_badge from "../components/badge";
import _comp_icon from "../components/icon";

// ── Singles ────────────────────────────────────────────────
import _fields from "../fields";
import _sidebar from "../sidebar";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface AdminCollections {
	account: typeof _coll_account;
	admin_locks: typeof _coll_admin_locks;
	admin_preferences: typeof _coll_admin_preferences;
	admin_saved_views: typeof _coll_admin_saved_views;
	apikey: typeof _coll_apikey;
	assets: typeof _coll_assets;
	session: typeof _coll_session;
	user: typeof _coll_user;
	verification: typeof _coll_verification;
}

export interface AdminViews {
	collectionForm: typeof _view_collectionForm;
	collectionTable: typeof _view_collectionTable;
	globalForm: typeof _view_globalForm;
}

export interface AdminComponents {
	badge: typeof _comp_badge;
	icon: typeof _comp_icon;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-admin" as const,
	modules: _modules,
	collections: {
		account: _coll_account,
		admin_locks: _coll_admin_locks,
		admin_preferences: _coll_admin_preferences,
		admin_saved_views: _coll_admin_saved_views,
		apikey: _coll_apikey,
		assets: _coll_assets,
		session: _coll_session,
		user: _coll_user,
		verification: _coll_verification,
	} as AdminCollections,
	functions: {
		..._fn_adminConfig,
		..._fn_executeAction,
		..._fn_locales,
		..._fn_preview,
		..._fn_reactive,
		..._fn_setup,
		..._fn_translations,
		..._fn_widgetData,
	},
	views: {
		collectionForm: _view_collectionForm,
		collectionTable: _view_collectionTable,
		globalForm: _view_globalForm,
	} as AdminViews,
	components: {
		badge: _comp_badge,
		icon: _comp_icon,
	} as AdminComponents,
	globals: {},
	jobs: {},
	routes: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	blocks: {},
	fields: _fields,
	sidebar: [_sidebar],
	dashboard: [] as const,
};

export type AdminModule = typeof _module;
export default _module;
