/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiPreviewRouteImport } from './routes/api/preview'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AppCitySlugRouteImport } from './routes/_app/$citySlug'
import { Route as AppCitySlugIndexRouteImport } from './routes/_app/$citySlug.index'
import { Route as ApiCmsSplatRouteImport } from './routes/api/cms/$'
import { Route as AppCitySlugPagesSlugRouteImport } from './routes/_app/$citySlug.pages.$slug'

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCitySlugRoute = AppCitySlugRouteImport.update({
  id: '/_app/$citySlug',
  path: '/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCitySlugIndexRoute = AppCitySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCitySlugRoute,
} as any)
const ApiCmsSplatRoute = ApiCmsSplatRouteImport.update({
  id: '/api/cms/$',
  path: '/api/cms/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCitySlugPagesSlugRoute = AppCitySlugPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => AppCitySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$citySlug': typeof AppCitySlugRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/api/preview': typeof ApiPreviewRoute
  '/admin': typeof AdminIndexRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
  '/$citySlug/': typeof AppCitySlugIndexRoute
  '/$citySlug/pages/$slug': typeof AppCitySlugPagesSlugRoute
}
export interface FileRoutesByTo {
  '/admin/$': typeof AdminSplatRoute
  '/api/preview': typeof ApiPreviewRoute
  '/admin': typeof AdminIndexRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
  '/$citySlug': typeof AppCitySlugIndexRoute
  '/$citySlug/pages/$slug': typeof AppCitySlugPagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/$citySlug': typeof AppCitySlugRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/api/preview': typeof ApiPreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
  '/_app/$citySlug/': typeof AppCitySlugIndexRoute
  '/_app/$citySlug/pages/$slug': typeof AppCitySlugPagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$citySlug'
    | '/admin/$'
    | '/api/preview'
    | '/admin'
    | '/api/cms/$'
    | '/$citySlug/'
    | '/$citySlug/pages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/$'
    | '/api/preview'
    | '/admin'
    | '/api/cms/$'
    | '/$citySlug'
    | '/$citySlug/pages/$slug'
  id:
    | '__root__'
    | '/_app/$citySlug'
    | '/admin/$'
    | '/api/preview'
    | '/admin/'
    | '/api/cms/$'
    | '/_app/$citySlug/'
    | '/_app/$citySlug/pages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppCitySlugRoute: typeof AppCitySlugRouteWithChildren
  AdminSplatRoute: typeof AdminSplatRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiCmsSplatRoute: typeof ApiCmsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$citySlug': {
      id: '/_app/$citySlug'
      path: '/$citySlug'
      fullPath: '/$citySlug'
      preLoaderRoute: typeof AppCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$citySlug/': {
      id: '/_app/$citySlug/'
      path: '/'
      fullPath: '/$citySlug/'
      preLoaderRoute: typeof AppCitySlugIndexRouteImport
      parentRoute: typeof AppCitySlugRoute
    }
    '/api/cms/$': {
      id: '/api/cms/$'
      path: '/api/cms/$'
      fullPath: '/api/cms/$'
      preLoaderRoute: typeof ApiCmsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$citySlug/pages/$slug': {
      id: '/_app/$citySlug/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/$citySlug/pages/$slug'
      preLoaderRoute: typeof AppCitySlugPagesSlugRouteImport
      parentRoute: typeof AppCitySlugRoute
    }
  }
}

interface AppCitySlugRouteChildren {
  AppCitySlugIndexRoute: typeof AppCitySlugIndexRoute
  AppCitySlugPagesSlugRoute: typeof AppCitySlugPagesSlugRoute
}

const AppCitySlugRouteChildren: AppCitySlugRouteChildren = {
  AppCitySlugIndexRoute: AppCitySlugIndexRoute,
  AppCitySlugPagesSlugRoute: AppCitySlugPagesSlugRoute,
}

const AppCitySlugRouteWithChildren = AppCitySlugRoute._addFileChildren(
  AppCitySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppCitySlugRoute: AppCitySlugRouteWithChildren,
  AdminSplatRoute: AdminSplatRoute,
  ApiPreviewRoute: ApiPreviewRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiCmsSplatRoute: ApiCmsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
