/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-core" as const,
	collections: {},
	globals: {},
	jobs: {},
	functions: {},
	routes: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
};

export type CoreModule = typeof _module;
export default _module;
