/**
 * Page Definition & Factory
 *
 * Defines custom admin pages outside of collections/globals.
 * The `page()` factory returns a plain frozen object.
 */

import type { MaybeLazyComponent } from "../types/common";

/**
 * Page definition — a plain frozen object describing a custom admin page.
 */
export interface PageDefinition<TName extends string = string> {
	readonly name: TName;
	readonly component: MaybeLazyComponent;
	readonly path?: string;
	readonly showInNav?: boolean;
}

/**
 * Create a custom page as a plain frozen object.
 *
 * @example
 * ```ts
 * // Generated by `questpie generate`:
 * export default page("login", {
 *   component: async () => ({
 *     default: (await import("./login-page.js")).LoginPage,
 *   }),
 *   showInNav: false,
 *   path: "/login",
 * });
 * ```
 */
export function page<
	TName extends string,
	TComponent extends MaybeLazyComponent,
>(
	name: TName,
	config: { component: TComponent; showInNav?: boolean; path?: string },
): PageDefinition<TName> {
	return Object.freeze({
		name,
		component: config.component,
		path: config.path,
		showInNav: config.showInNav,
	});
}
