/**
 * Admin Client Config
 *
 * Auto-generated by questpie codegen — do not edit.
 *
 * Pass this directly to <AdminLayoutProvider admin={admin} />
 */

import { AccordionRenderer as _block_accordion } from "../blocks/accordion";
import { CTARenderer as _block_cta } from "../blocks/cta";
import { LatestNewsRenderer as _block_dynamic } from "../blocks/dynamic";
import { GalleryRenderer as _block_gallery } from "../blocks/gallery";
import { HeadingRenderer as _block_heading } from "../blocks/heading";
import { HeroRenderer as _block_hero } from "../blocks/hero";
import { ImageRenderer as _block_image } from "../blocks/image";
import { ImageTextRenderer as _block_imageText } from "../blocks/image-text";
import { ColumnsRenderer as _block_layout } from "../blocks/layout";
import { TextRenderer as _block_text } from "../blocks/text";
import { VideoRenderer as _block_video } from "../blocks/video";
import type { BlockRendererProps } from "@questpie/admin/client";
import type { InferBlockValues, InferBlockData } from "@questpie/admin/server";
import type { accordionBlock } from "../../server/blocks/accordion";
import type { ctaBlock } from "../../server/blocks/cta";
import type { dynamicBlock } from "../../server/blocks/dynamic";
import type { galleryBlock } from "../../server/blocks/gallery";
import type { headingBlock } from "../../server/blocks/heading";
import type { heroBlock } from "../../server/blocks/hero";
import type { imageBlock } from "../../server/blocks/image";
import type { imageTextBlock } from "../../server/blocks/image-text";
import type { layoutBlock } from "../../server/blocks/layout";
import type { textBlock } from "../../server/blocks/text";
import type { videoBlock } from "../../server/blocks/video";

const admin = {
	blocks: { "accordion": _block_accordion, "cta": _block_cta, "dynamic": _block_dynamic, "gallery": _block_gallery, "heading": _block_heading, "hero": _block_hero, "image": _block_image, "imageText": _block_imageText, "layout": _block_layout, "text": _block_text, "video": _block_video },
};

type _ServerBlocks = { "accordion": typeof accordionBlock; "cta": typeof ctaBlock; "dynamic": typeof dynamicBlock; "gallery": typeof galleryBlock; "heading": typeof headingBlock; "hero": typeof heroBlock; "image": typeof imageBlock; "imageText": typeof imageTextBlock; "layout": typeof layoutBlock; "text": typeof textBlock; "video": typeof videoBlock };

export type BlockProps<T extends keyof _ServerBlocks> = BlockRendererProps<
	InferBlockValues<_ServerBlocks[T]["state"]>,
	InferBlockData<_ServerBlocks[T]>
>;

export default admin;
